INSERT INTO localization00 (key, language_code, textcontent, component) VALUES
('accommodationFormTypeHotel', 'en', 'Hotel', 'AccommodationForm'),
('accommodationFormTypeResort', 'en', 'Resort', 'AccommodationForm'),
('accommodationFormTypeServicedResidences', 'en', 'Serviced Residences', 'AccommodationForm'),
('accommodationFormTypePensionLodginghouse', 'en', 'Pension/Lodging house', 'AccommodationForm'),
('accommodationFormTypeTouristInnMotelDriveIn', 'en', 'Tourist Inn/Motel/Drive-In', 'AccommodationForm'),
('accommodationFormTypeHomestay', 'en', 'Homestay', 'AccommodationForm'),
('accommodationFormCommercialQuestion', 'en', 'Did you stay/Are you staying in a commercial accommodation?', 'AccommodationForm'),
('accommodationFormYesButton', 'en', 'YES', 'AccommodationForm'),
('accommodationFormNoButton', 'en', 'NO', 'AccommodationForm'),
('accommodationFormTypesAndLengthQuestion', 'en', 'What types and length of stay?', 'AccommodationForm'),
('accommodationFormNameHeader', 'en', 'NAME', 'AccommodationForm'),
('accommodationFormRatingHeader', 'en', 'RATING (1-4)', 'AccommodationForm'),
('accommodationFormDurationHeader', 'en', 'DURATION (IN DAYS)', 'AccommodationForm'),
('accommodationFormDaysPlaceholder', 'en', 'Days', 'AccommodationForm'),
('accommodationFormNextButton', 'en', 'Next', 'AccommodationForm');

INSERT INTO localization00 (key, language_code, textcontent, component) VALUES


('accommodationFormTypeHotel', 'ko', '호텔', 'AccommodationForm'),
('accommodationFormTypeResort', 'ko', '리조트', 'AccommodationForm'),
('accommodationFormTypeServicedResidences', 'ko', '서비스드 레지던스', 'AccommodationForm'),
('accommodationFormTypePensionLodginghouse', 'ko', '펜션/여관', 'AccommodationForm'),
('accommodationFormTypeTouristInnMotelDriveIn', 'ko', '관광 여관/모텔/드라이브 인', 'AccommodationForm'),
('accommodationFormTypeHomestay', 'ko', '홈스테이', 'AccommodationForm'),
('accommodationFormCommercialQuestion', 'ko', '상업적 숙소에 머무셨나요/머무시나요?', 'AccommodationForm'),
('accommodationFormYesButton', 'ko', '예', 'AccommodationForm'),
('accommodationFormNoButton', 'ko', '아니오', 'AccommodationForm'),
('accommodationFormTypesAndLengthQuestion', 'ko', '어떤 유형과 기간으로 숙박하셨나요?', 'AccommodationForm'),
('accommodationFormNameHeader', 'ko', '이름', 'AccommodationForm'),
('accommodationFormRatingHeader', 'ko', '등급 (1-4)', 'AccommodationForm'),
('accommodationFormDurationHeader', 'ko', '기간 (일수)', 'AccommodationForm'),
('accommodationFormDaysPlaceholder', 'ko', '일', 'AccommodationForm'),
('accommodationFormNextButton', 'ko', '다음', 'AccommodationForm'),

('accommodationFormTypeHotel', 'zh', '酒店', 'AccommodationForm'),
('accommodationFormTypeResort', 'zh', '度假村', 'AccommodationForm'),
('accommodationFormTypeServicedResidences', 'zh', '服务式公寓', 'AccommodationForm'),
('accommodationFormTypePensionLodginghouse', 'zh', '旅馆/住宿舍', 'AccommodationForm'),
('accommodationFormTypeTouristInnMotelDriveIn', 'zh', '旅游旅馆/汽车旅馆/自驾酒店', 'AccommodationForm'),
('accommodationFormTypeHomestay', 'zh', '民宿', 'AccommodationForm'),
('accommodationFormCommercialQuestion', 'zh', '您曾住过/正在住在商业住宿设施中吗？', 'AccommodationForm'),
('accommodationFormYesButton', 'zh', '是', 'AccommodationForm'),
('accommodationFormNoButton', 'zh', '否', 'AccommodationForm'),
('accommodationFormTypesAndLengthQuestion', 'zh', '您住过哪种类型的住宿，停留时间多长？', 'AccommodationForm'),
('accommodationFormNameHeader', 'zh', '姓名', 'AccommodationForm'),
('accommodationFormRatingHeader', 'zh', '评级 (1-4)', 'AccommodationForm'),
('accommodationFormDurationHeader', 'zh', '停留时间（天数）', 'AccommodationForm'),
('accommodationFormDaysPlaceholder', 'zh', '天', 'AccommodationForm'),
('accommodationFormNextButton', 'zh', '下一步', 'AccommodationForm'),

('accommodationFormTypeHotel', 'ja', 'ホテル', 'AccommodationForm'),
('accommodationFormTypeResort', 'ja', 'リゾート', 'AccommodationForm'),
('accommodationFormTypeServicedResidences', 'ja', 'サービス付き住宅', 'AccommodationForm'),
('accommodationFormTypePensionLodginghouse', 'ja', 'ペンション/宿泊施設', 'AccommodationForm'),
('accommodationFormTypeTouristInnMotelDriveIn', 'ja', '観光ホテル/モーテル/ドライブイン', 'AccommodationForm'),
('accommodationFormTypeHomestay', 'ja', 'ホームステイ', 'AccommodationForm'),
('accommodationFormCommercialQuestion', 'ja', '商業施設に宿泊しましたか/宿泊していますか？', 'AccommodationForm'),
('accommodationFormYesButton', 'ja', 'はい', 'AccommodationForm'),
('accommodationFormNoButton', 'ja', 'いいえ', 'AccommodationForm'),
('accommodationFormTypesAndLengthQuestion', 'ja', 'どのタイプの宿泊施設にどれくらいの期間宿泊しましたか？', 'AccommodationForm'),
('accommodationFormNameHeader', 'ja', '名前', 'AccommodationForm'),
('accommodationFormRatingHeader', 'ja', '評価 (1-4)', 'AccommodationForm'),
('accommodationFormDurationHeader', 'ja', '滞在期間（日数）', 'AccommodationForm'),
('accommodationFormDaysPlaceholder', 'ja', '日', 'AccommodationForm'),
('accommodationFormNextButton', 'ja', '次へ', 'AccommodationForm'),

('accommodationFormTypeHotel', 'es', 'Hotel', 'AccommodationForm'),
('accommodationFormTypeResort', 'es', 'Resort', 'AccommodationForm'),
('accommodationFormTypeServicedResidences', 'es', 'Residencias con servicios', 'AccommodationForm'),
('accommodationFormTypePensionLodginghouse', 'es', 'Pensión/Casa de huéspedes', 'AccommodationForm'),
('accommodationFormTypeTouristInnMotelDriveIn', 'es', 'Posada/Motel/Drive-In', 'AccommodationForm'),
('accommodationFormTypeHomestay', 'es', 'Casa de huéspedes', 'AccommodationForm'),
('accommodationFormCommercialQuestion', 'es', '¿Te hospedaste/Estás hospedado en un alojamiento comercial?', 'AccommodationForm'),
('accommodationFormYesButton', 'es', 'SÍ', 'AccommodationForm'),
('accommodationFormNoButton', 'es', 'NO', 'AccommodationForm'),
('accommodationFormTypesAndLengthQuestion', 'es', '¿Qué tipo de alojamiento y por cuánto tiempo?', 'AccommodationForm'),
('accommodationFormNameHeader', 'es', 'NOMBRE', 'AccommodationForm'),
('accommodationFormRatingHeader', 'es', 'CALIFICACIÓN (1-4)', 'AccommodationForm'),
('accommodationFormDurationHeader', 'es', 'DURACIÓN (EN DÍAS)', 'AccommodationForm'),
('accommodationFormDaysPlaceholder', 'es', 'Días', 'AccommodationForm'),
('accommodationFormNextButton', 'es', 'Siguiente', 'AccommodationForm'),

('accommodationFormTypeHotel', 'fr', 'Hôtel', 'AccommodationForm'),
('accommodationFormTypeResort', 'fr', 'Station balnéaire', 'AccommodationForm'),
('accommodationFormTypeServicedResidences', 'fr', 'Résidences avec services', 'AccommodationForm'),
('accommodationFormTypePensionLodginghouse', 'fr', 'Pension/Chambre d’hôtes', 'AccommodationForm'),
('accommodationFormTypeTouristInnMotelDriveIn', 'fr', 'Auberge/Motel/Drive-In', 'AccommodationForm'),
('accommodationFormTypeHomestay', 'fr', 'Séjour chez l’habitant', 'AccommodationForm'),
('accommodationFormCommercialQuestion', 'fr', 'Avez-vous séjourné/êtes-vous en séjour dans un hébergement commercial ?', 'AccommodationForm'),
('accommodationFormYesButton', 'fr', 'OUI', 'AccommodationForm'),
('accommodationFormNoButton', 'fr', 'NON', 'AccommodationForm'),
('accommodationFormTypesAndLengthQuestion', 'fr', 'Quel type d’hébergement et quelle durée de séjour ?', 'AccommodationForm'),
('accommodationFormNameHeader', 'fr', 'NOM', 'AccommodationForm'),
('accommodationFormRatingHeader', 'fr', 'ÉVALUATION (1-4)', 'AccommodationForm'),
('accommodationFormDurationHeader', 'fr', 'DURÉE (EN JOURS)', 'AccommodationForm'),
('accommodationFormDaysPlaceholder', 'fr', 'Jours', 'AccommodationForm'),
('accommodationFormNextButton', 'fr', 'Suivant', 'AccommodationForm'),

('accommodationFormTypeHotel', 'hi', 'होटल', 'AccommodationForm'),
('accommodationFormTypeResort', 'hi', 'रिसॉर्ट', 'AccommodationForm'),
('accommodationFormTypeServicedResidences', 'hi', 'सर्विस्ड रेजिडेंसेस', 'AccommodationForm'),
('accommodationFormTypePensionLodginghouse', 'hi', 'पेंशन/लॉजिंग हाउस', 'AccommodationForm'),
('accommodationFormTypeTouristInnMotelDriveIn', 'hi', 'टूरिस्ट इन/मोटल/ड्राइव-इन', 'AccommodationForm'),
('accommodationFormTypeHomestay', 'hi', 'होमस्टे', 'AccommodationForm'),
('accommodationFormCommercialQuestion', 'hi', 'क्या आपने/क्या आप किसी वाणिज्यिक आवास में ठहरे थे/ठहर रहे हैं?', 'AccommodationForm'),
('accommodationFormYesButton', 'hi', 'हां', 'AccommodationForm'),
('accommodationFormNoButton', 'hi', 'नहीं', 'AccommodationForm'),
('accommodationFormTypesAndLengthQuestion', 'hi', 'किस प्रकार के और कितने समय का आवास?', 'AccommodationForm'),
('accommodationFormNameHeader', 'hi', 'नाम', 'AccommodationForm'),
('accommodationFormRatingHeader', 'hi', 'रेटिंग (1-4)', 'AccommodationForm'),
('accommodationFormDurationHeader', 'hi', 'अवधि (दिनों में)', 'AccommodationForm'),
('accommodationFormDaysPlaceholder', 'hi', 'दिन', 'AccommodationForm'),
('accommodationFormNextButton', 'hi', 'अगला', 'AccommodationForm'),

('accommodationFormTypeHotel', 'ru', 'Отель', 'AccommodationForm'),
('accommodationFormTypeResort', 'ru', 'Курорт', 'AccommodationForm'),
('accommodationFormTypeServicedResidences', 'ru', 'Сервисные квартиры', 'AccommodationForm'),
('accommodationFormTypePensionLodginghouse', 'ru', 'Пансион/Гостевой дом', 'AccommodationForm'),
('accommodationFormTypeTouristInnMotelDriveIn', 'ru', 'Туристический отель/Мотель/Drive-In', 'AccommodationForm'),
('accommodationFormTypeHomestay', 'ru', 'Гостевой дом', 'AccommodationForm'),
('accommodationFormCommercialQuestion', 'ru', 'Вы останавливались/остаетесь в коммерческом жилье?', 'AccommodationForm'),
('accommodationFormYesButton', 'ru', 'ДА', 'AccommodationForm'),
('accommodationFormNoButton', 'ru', 'НЕТ', 'AccommodationForm'),
('accommodationFormTypesAndLengthQuestion', 'ru', 'Какие типы и продолжительность пребывания?', 'AccommodationForm'),
('accommodationFormNameHeader', 'ru', 'ИМЯ', 'AccommodationForm'),
('accommodationFormRatingHeader', 'ru', 'РЕЙТИНГ (1-4)', 'AccommodationForm'),
('accommodationFormDurationHeader', 'ru', 'ПРОДОЛЖИТЕЛЬНОСТЬ (В ДНЯХ)', 'AccommodationForm'),
('accommodationFormDaysPlaceholder', 'ru', 'Дни', 'AccommodationForm'),
('accommodationFormNextButton', 'ru', 'Далее', 'AccommodationForm');
