INSERT INTO localization00 (key, language_code, textcontent, component) VALUES
('attractionFormTitle', 'en', 'Events Enumeration', 'AttractionForm'),
('attractionFormHeaderAttraction', 'en', 'Tourist Attraction/Activities', 'AttractionForm'),
('attractionFormHeaderLocation', 'en', 'Location', 'AttractionForm'),
('attractionFormHeaderRating', 'en', 'Rating', 'AttractionForm'),
('attractionFormHeaderDelete', 'en', 'Delete', 'AttractionForm'),
('attractionFormPlaceholderAttraction', 'en', 'Enter attraction/activity', 'AttractionForm'),
('attractionFormPlaceholderLocation', 'en', 'Enter location', 'AttractionForm'),
('attractionFormButtonAddRow', 'en', 'Add Row', 'AttractionForm'),
('attractionFormButtonNext', 'en', 'Next', 'AttractionForm'),
('attractionFormErrorAllFields', 'en', 'All fields must be filled out!', 'AttractionForm'),
('attractionFormRowAdded', 'en', 'Row added successfully!', 'AttractionForm'),
('attractionFormRowDeleted', 'en', 'Row deleted!', 'AttractionForm'),

-- Korean Localizations
('attractionFormTitle', 'ko', '이벤트 목록', 'AttractionForm'),
('attractionFormHeaderAttraction', 'ko', '관광 명소/활동', 'AttractionForm'),
('attractionFormHeaderLocation', 'ko', '위치', 'AttractionForm'),
('attractionFormHeaderRating', 'ko', '평점', 'AttractionForm'),
('attractionFormHeaderDelete', 'ko', '삭제', 'AttractionForm'),
('attractionFormPlaceholderAttraction', 'ko', '명소/활동을 입력하세요', 'AttractionForm'),
('attractionFormPlaceholderLocation', 'ko', '위치를 입력하세요', 'AttractionForm'),
('attractionFormButtonAddRow', 'ko', '행 추가', 'AttractionForm'),
('attractionFormButtonNext', 'ko', '다음', 'AttractionForm'),
('attractionFormErrorAllFields', 'ko', '모든 필드를 작성해야 합니다!', 'AttractionForm'),
('attractionFormRowAdded', 'ko', '행이 성공적으로 추가되었습니다!', 'AttractionForm'),
('attractionFormRowDeleted', 'ko', '행이 삭제되었습니다!', 'AttractionForm'),

-- Chinese Localizations
('attractionFormTitle', 'zh', '事件枚举', 'AttractionForm'),
('attractionFormHeaderAttraction', 'zh', '旅游景点/活动', 'AttractionForm'),
('attractionFormHeaderLocation', 'zh', '位置', 'AttractionForm'),
('attractionFormHeaderRating', 'zh', '评分', 'AttractionForm'),
('attractionFormHeaderDelete', 'zh', '删除', 'AttractionForm'),
('attractionFormPlaceholderAttraction', 'zh', '请输入景点/活动', 'AttractionForm'),
('attractionFormPlaceholderLocation', 'zh', '请输入位置', 'AttractionForm'),
('attractionFormButtonAddRow', 'zh', '添加行', 'AttractionForm'),
('attractionFormButtonNext', 'zh', '下一步', 'AttractionForm'),
('attractionFormErrorAllFields', 'zh', '所有字段必须填写!', 'AttractionForm'),
('attractionFormRowAdded', 'zh', '行添加成功!', 'AttractionForm'),
('attractionFormRowDeleted', 'zh', '行已删除!', 'AttractionForm'),

-- Japanese Localizations
('attractionFormTitle', 'ja', 'イベントの列挙', 'AttractionForm'),
('attractionFormHeaderAttraction', 'ja', '観光地/アクティビティ', 'AttractionForm'),
('attractionFormHeaderLocation', 'ja', '場所', 'AttractionForm'),
('attractionFormHeaderRating', 'ja', '評価', 'AttractionForm'),
('attractionFormHeaderDelete', 'ja', '削除', 'AttractionForm'),
('attractionFormPlaceholderAttraction', 'ja', '観光地/アクティビティを入力', 'AttractionForm'),
('attractionFormPlaceholderLocation', 'ja', '場所を入力', 'AttractionForm'),
('attractionFormButtonAddRow', 'ja', '行を追加', 'AttractionForm'),
('attractionFormButtonNext', 'ja', '次へ', 'AttractionForm'),
('attractionFormErrorAllFields', 'ja', 'すべてのフィールドを記入してください!', 'AttractionForm'),
('attractionFormRowAdded', 'ja', '行が正常に追加されました!', 'AttractionForm'),
('attractionFormRowDeleted', 'ja', '行が削除されました!', 'AttractionForm'),

-- Spanish Localizations
('attractionFormTitle', 'es', 'Enumeración de eventos', 'AttractionForm'),
('attractionFormHeaderAttraction', 'es', 'Atracción/Actividad turística', 'AttractionForm'),
('attractionFormHeaderLocation', 'es', 'Ubicación', 'AttractionForm'),
('attractionFormHeaderRating', 'es', 'Calificación', 'AttractionForm'),
('attractionFormHeaderDelete', 'es', 'Eliminar', 'AttractionForm'),
('attractionFormPlaceholderAttraction', 'es', 'Introduzca la atracción/actividad', 'AttractionForm'),
('attractionFormPlaceholderLocation', 'es', 'Introduzca la ubicación', 'AttractionForm'),
('attractionFormButtonAddRow', 'es', 'Agregar fila', 'AttractionForm'),
('attractionFormButtonNext', 'es', 'Siguiente', 'AttractionForm'),
('attractionFormErrorAllFields', 'es', '¡Todos los campos deben ser completados!', 'AttractionForm'),
('attractionFormRowAdded', 'es', '¡Fila añadida con éxito!', 'AttractionForm'),
('attractionFormRowDeleted', 'es', '¡Fila eliminada!', 'AttractionForm'),

-- French Localizations
('attractionFormTitle', 'fr', 'Énumération des événements', 'AttractionForm'),
('attractionFormHeaderAttraction', 'fr', 'Attraction/Activité touristique', 'AttractionForm'),
('attractionFormHeaderLocation', 'fr', 'Lieu', 'AttractionForm'),
('attractionFormHeaderRating', 'fr', 'Évaluation', 'AttractionForm'),
('attractionFormHeaderDelete', 'fr', 'Supprimer', 'AttractionForm'),
('attractionFormPlaceholderAttraction', 'fr', 'Entrez l''attraction/activité', 'AttractionForm'),
('attractionFormPlaceholderLocation', 'fr', 'Entrez l''emplacement', 'AttractionForm'),
('attractionFormButtonAddRow', 'fr', 'Ajouter une ligne', 'AttractionForm'),
('attractionFormButtonNext', 'fr', 'Suivant', 'AttractionForm'),
('attractionFormErrorAllFields', 'fr', 'Tous les champs doivent être remplis!', 'AttractionForm'),
('attractionFormRowAdded', 'fr', 'Ligne ajoutée avec succès!', 'AttractionForm'),
('attractionFormRowDeleted', 'fr', 'Ligne supprimée!', 'AttractionForm'),

-- Hindi Localizations
('attractionFormTitle', 'hi', 'इवेंट्स सूची', 'AttractionForm'),
('attractionFormHeaderAttraction', 'hi', 'पर्यटन स्थल/गतिविधियाँ', 'AttractionForm'),
('attractionFormHeaderLocation', 'hi', 'स्थान', 'AttractionForm'),
('attractionFormHeaderRating', 'hi', 'रेटिंग', 'AttractionForm'),
('attractionFormHeaderDelete', 'hi', 'हटाएं', 'AttractionForm'),
('attractionFormPlaceholderAttraction', 'hi', 'पर्यटन स्थल/गतिविधि दर्ज करें', 'AttractionForm'),
('attractionFormPlaceholderLocation', 'hi', 'स्थान दर्ज करें', 'AttractionForm'),
('attractionFormButtonAddRow', 'hi', 'पंक्ति जोड़ें', 'AttractionForm'),
('attractionFormButtonNext', 'hi', 'अगला', 'AttractionForm'),
('attractionFormErrorAllFields', 'hi', 'सभी फ़ील्ड भरने होंगे!', 'AttractionForm'),
('attractionFormRowAdded', 'hi', 'पंक्ति सफलतापूर्वक जोड़ी गई!', 'AttractionForm'),
('attractionFormRowDeleted', 'hi', 'पंक्ति हटा दी गई!', 'AttractionForm'),

-- Russian Localizations
('attractionFormTitle', 'ru', 'Перечень событий', 'AttractionForm'),
('attractionFormHeaderAttraction', 'ru', 'Туристическая достопримечательность/Активности', 'AttractionForm'),
('attractionFormHeaderLocation', 'ru', 'Местоположение', 'AttractionForm'),
('attractionFormHeaderRating', 'ru', 'Рейтинг', 'AttractionForm'),
('attractionFormHeaderDelete', 'ru', 'Удалить', 'AttractionForm'),
('attractionFormPlaceholderAttraction', 'ru', 'Введите достопримечательность/активность', 'AttractionForm'),
('attractionFormPlaceholderLocation', 'ru', 'Введите местоположение', 'AttractionForm'),
('attractionFormButtonAddRow', 'ru', 'Добавить строку', 'AttractionForm'),
('attractionFormButtonNext', 'ru', 'Далее', 'AttractionForm'),
('attractionFormErrorAllFields', 'ru', 'Все поля должны быть заполнены!', 'AttractionForm'),
('attractionFormRowAdded', 'ru', 'Строка успешно добавлена!', 'AttractionForm'),
('attractionFormRowDeleted', 'ru', 'Строка удалена!', 'AttractionForm');
