INSERT INTO localization00 (key, language_code, textcontent, component) VALUES
('bookingFormBookingMethodLabel', 'en', 'What booking method was used?', 'BookingForm'),
('bookingFormBookingMethodLabel', 'ko', '어떤 예약 방법을 사용했습니까?', 'BookingForm'),
('bookingFormBookingMethodLabel', 'zh', '使用了哪种预订方式?', 'BookingForm'),
('bookingFormBookingMethodLabel', 'ja', 'どの予約方法を使用しましたか？', 'BookingForm'),
('bookingFormBookingMethodLabel', 'es', '¿Qué método de reserva se utilizó?', 'BookingForm'),
('bookingFormBookingMethodLabel', 'fr', 'Quelle méthode de réservation a été utilisée ?', 'BookingForm'),
('bookingFormBookingMethodLabel', 'hi', 'कौन सी बुकिंग विधि का उपयोग किया गया?', 'BookingForm'),
('bookingFormBookingMethodLabel', 'ru', 'Какой метод бронирования был использован?', 'BookingForm'),

('bookingFormSelectBookingMethod', 'en', 'Select Booking Method', 'BookingForm'),
('bookingFormSelectBookingMethod', 'ko', '예약 방법 선택', 'BookingForm'),
('bookingFormSelectBookingMethod', 'zh', '选择预订方式', 'BookingForm'),
('bookingFormSelectBookingMethod', 'ja', '予約方法を選択', 'BookingForm'),
('bookingFormSelectBookingMethod', 'es', 'Seleccione el método de reserva', 'BookingForm'),
('bookingFormSelectBookingMethod', 'fr', 'Sélectionnez la méthode de réservation', 'BookingForm'),
('bookingFormSelectBookingMethod', 'hi', 'बुकिंग विधि चुनें', 'BookingForm'),
('bookingFormSelectBookingMethod', 'ru', 'Выберите метод бронирования', 'BookingForm'),

('bookingFormBookingPlatformLabel', 'en', 'Booking platform?', 'BookingForm'),
('bookingFormBookingPlatformLabel', 'ko', '예약 플랫폼?', 'BookingForm'),
('bookingFormBookingPlatformLabel', 'zh', '预订平台？', 'BookingForm'),
('bookingFormBookingPlatformLabel', 'ja', '予約プラットフォームは？', 'BookingForm'),
('bookingFormBookingPlatformLabel', 'es', '¿Plataforma de reserva?', 'BookingForm'),
('bookingFormBookingPlatformLabel', 'fr', 'Plateforme de réservation ?', 'BookingForm'),
('bookingFormBookingPlatformLabel', 'hi', 'बुकिंग प्लेटफॉर्म?', 'BookingForm'),
('bookingFormBookingPlatformLabel', 'ru', 'Платформа для бронирования?', 'BookingForm'),

('bookingFormSelectBookingPlatform', 'en', 'Select Booking Platform', 'BookingForm'),
('bookingFormSelectBookingPlatform', 'ko', '예약 플랫폼 선택', 'BookingForm'),
('bookingFormSelectBookingPlatform', 'zh', '选择预订平台', 'BookingForm'),
('bookingFormSelectBookingPlatform', 'ja', '予約プラットフォームを選択', 'BookingForm'),
('bookingFormSelectBookingPlatform', 'es', 'Seleccione la plataforma de reserva', 'BookingForm'),
('bookingFormSelectBookingPlatform', 'fr', 'Sélectionnez la plateforme de réservation', 'BookingForm'),
('bookingFormSelectBookingPlatform', 'hi', 'बुकिंग प्लेटफॉर्म चुनें', 'BookingForm'),
('bookingFormSelectBookingPlatform', 'ru', 'Выберите платформу для бронирования', 'BookingForm'),

('bookingFormOthersSpecifyLabel', 'en', 'Others (specify)', 'BookingForm'),
('bookingFormOthersSpecifyLabel', 'ko', '기타 (명시)', 'BookingForm'),
('bookingFormOthersSpecifyLabel', 'zh', '其他（请注明）', 'BookingForm'),
('bookingFormOthersSpecifyLabel', 'ja', 'その他（指定）', 'BookingForm'),
('bookingFormOthersSpecifyLabel', 'es', 'Otros (especificar)', 'BookingForm'),
('bookingFormOthersSpecifyLabel', 'fr', 'Autres (préciser)', 'BookingForm'),
('bookingFormOthersSpecifyLabel', 'hi', 'अन्य (निर्दिष्ट करें)', 'BookingForm'),
('bookingFormOthersSpecifyLabel', 'ru', 'Другие (уточните)', 'BookingForm'),

('bookingFormNextButton', 'en', 'Next', 'BookingForm'),
('bookingFormNextButton', 'ko', '다음', 'BookingForm'),
('bookingFormNextButton', 'zh', '下一步', 'BookingForm'),
('bookingFormNextButton', 'ja', '次へ', 'BookingForm'),
('bookingFormNextButton', 'es', 'Siguiente', 'BookingForm'),
('bookingFormNextButton', 'fr', 'Suivant', 'BookingForm'),
('bookingFormNextButton', 'hi', 'अगला', 'BookingForm'),
('bookingFormNextButton', 'ru', 'Далее', 'BookingForm');
