INSERT INTO localization00 (key, language_code, textcontent, component) VALUES
-- English
('expenseTrackerTitle', 'en', 'How much did you spend or plan to spend here in the destination?', 'ExpenseTracker'),
('expenseTrackerAccommodation', 'en', 'Accommodation', 'ExpenseTracker'),
('expenseTrackerFoodandBeverage', 'en', 'Food and Beverage', 'ExpenseTracker'),
('expenseTrackerShopping', 'en', 'Shopping', 'ExpenseTracker'),
('expenseTrackerLocalTransport', 'en', 'Local Transport', 'ExpenseTracker'),
('expenseTrackerTourismActivitiesEntertainment', 'en', 'Tourism Activities/Entertainment', 'ExpenseTracker'),
('expenseTrackerMiscellaneous', 'en', 'Miscellaneous', 'ExpenseTracker'),
('expenseTrackerSummaryTitle', 'en', 'Summary of Expenses', 'ExpenseTracker'),
('expenseTrackerTotalInCurrency', 'en', 'Total in', 'ExpenseTracker'),
('expenseTrackerTotalInPHP', 'en', 'Total in PHP', 'ExpenseTracker'),
('expenseTrackerNextButton', 'en', 'Next', 'ExpenseTracker'),
('expenseTrackerForgetButton', 'en', 'I CAN''T REMEMBER / DISCLOSE', 'ExpenseTracker'),

-- Korean
('expenseTrackerTitle', 'ko', '여행지에서 얼마를 사용하거나 계획하셨나요?', 'ExpenseTracker'),
('expenseTrackerAccommodation', 'ko', '숙박', 'ExpenseTracker'),
('expenseTrackerFoodandBeverage', 'ko', '음식 및 음료', 'ExpenseTracker'),
('expenseTrackerShopping', 'ko', '쇼핑', 'ExpenseTracker'),
('expenseTrackerLocalTransport', 'ko', '교통', 'ExpenseTracker'),
('expenseTrackerTourismActivitiesEntertainment', 'ko', '관광/엔터테인먼트', 'ExpenseTracker'),
('expenseTrackerMiscellaneous', 'ko', '기타', 'ExpenseTracker'),
('expenseTrackerSummaryTitle', 'ko', '지출 요약', 'ExpenseTracker'),
('expenseTrackerTotalInCurrency', 'ko', '총계', 'ExpenseTracker'),
('expenseTrackerTotalInPHP', 'ko', 'PHP로 환산된 총계', 'ExpenseTracker'),
('expenseTrackerNextButton', 'ko', '다음', 'ExpenseTracker'),
('expenseTrackerForgetButton', 'ko', '기억이 안 납니다 / 공개할 수 없습니다', 'ExpenseTracker'),

-- Chinese
('expenseTrackerTitle', 'zh', '您在目的地花费或计划花费了多少？', 'ExpenseTracker'),
('expenseTrackerAccommodation', 'zh', '住宿', 'ExpenseTracker'),
('expenseTrackerFoodandBeverage', 'zh', '餐饮', 'ExpenseTracker'),
('expenseTrackerShopping', 'zh', '购物', 'ExpenseTracker'),
('expenseTrackerLocalTransport', 'zh', '本地交通', 'ExpenseTracker'),
('expenseTrackerTourismActivitiesEntertainment', 'zh', '旅游活动/娱乐', 'ExpenseTracker'),
('expenseTrackerMiscellaneous', 'zh', '其他', 'ExpenseTracker'),
('expenseTrackerSummaryTitle', 'zh', '费用总结', 'ExpenseTracker'),
('expenseTrackerTotalInCurrency', 'zh', '总计', 'ExpenseTracker'),
('expenseTrackerTotalInPHP', 'zh', '以PHP计总额', 'ExpenseTracker'),
('expenseTrackerNextButton', 'zh', '下一步', 'ExpenseTracker'),
('expenseTrackerForgetButton', 'zh', '我不记得 / 无法透露', 'ExpenseTracker'),

-- Japanese
('expenseTrackerTitle', 'ja', '目的地でいくら使いましたか、または使う予定ですか？', 'ExpenseTracker'),
('expenseTrackerAccommodation', 'ja', '宿泊', 'ExpenseTracker'),
('expenseTrackerFoodandBeverage', 'ja', '飲食', 'ExpenseTracker'),
('expenseTrackerShopping', 'ja', 'ショッピング', 'ExpenseTracker'),
('expenseTrackerLocalTransport', 'ja', '交通機関', 'ExpenseTracker'),
('expenseTrackerTourismActivitiesEntertainment', 'ja', '観光活動/エンターテイメント', 'ExpenseTracker'),
('expenseTrackerMiscellaneous', 'ja', 'その他', 'ExpenseTracker'),
('expenseTrackerSummaryTitle', 'ja', '費用の概要', 'ExpenseTracker'),
('expenseTrackerTotalInCurrency', 'ja', '合計', 'ExpenseTracker'),
('expenseTrackerTotalInPHP', 'ja', 'PHPでの合計', 'ExpenseTracker'),
('expenseTrackerNextButton', 'ja', '次へ', 'ExpenseTracker'),
('expenseTrackerForgetButton', 'ja', '覚えていません / 開示できません', 'ExpenseTracker'),

-- Spanish
('expenseTrackerTitle', 'es', '¿Cuánto gastaste o planeas gastar aquí en el destino?', 'ExpenseTracker'),
('expenseTrackerAccommodation', 'es', 'Alojamiento', 'ExpenseTracker'),
('expenseTrackerFoodandBeverage', 'es', 'Comida y Bebida', 'ExpenseTracker'),
('expenseTrackerShopping', 'es', 'Compras', 'ExpenseTracker'),
('expenseTrackerLocalTransport', 'es', 'Transporte Local', 'ExpenseTracker'),
('expenseTrackerTourismActivitiesEntertainment', 'es', 'Actividades Turísticas/Entretenimiento', 'ExpenseTracker'),
('expenseTrackerMiscellaneous', 'es', 'Misceláneo', 'ExpenseTracker'),
('expenseTrackerSummaryTitle', 'es', 'Resumen de Gastos', 'ExpenseTracker'),
('expenseTrackerTotalInCurrency', 'es', 'Total en', 'ExpenseTracker'),
('expenseTrackerTotalInPHP', 'es', 'Total en PHP', 'ExpenseTracker'),
('expenseTrackerNextButton', 'es', 'Siguiente', 'ExpenseTracker'),
('expenseTrackerForgetButton', 'es', 'NO RECUERDO / NO PUEDO DIVULGAR', 'ExpenseTracker'),

-- French
('expenseTrackerTitle', 'fr', 'Combien avez-vous dépensé ou prévoyez-vous de dépenser ici à destination ?', 'ExpenseTracker'),
('expenseTrackerAccommodation', 'fr', 'Hébergement', 'ExpenseTracker'),
('expenseTrackerFoodandBeverage', 'fr', 'Nourriture et Boisson', 'ExpenseTracker'),
('expenseTrackerShopping', 'fr', 'Achats', 'ExpenseTracker'),
('expenseTrackerLocalTransport', 'fr', 'Transport Local', 'ExpenseTracker'),
('expenseTrackerTourismActivitiesEntertainment', 'fr', 'Activités Touristiques/Divertissement', 'ExpenseTracker'),
('expenseTrackerMiscellaneous', 'fr', 'Divers', 'ExpenseTracker'),
('expenseTrackerSummaryTitle', 'fr', 'Résumé des Dépenses', 'ExpenseTracker'),
('expenseTrackerTotalInCurrency', 'fr', 'Total en', 'ExpenseTracker'),
('expenseTrackerTotalInPHP', 'fr', 'Total en PHP', 'ExpenseTracker'),
('expenseTrackerNextButton', 'fr', 'Suivant', 'ExpenseTracker'),
('expenseTrackerForgetButton', 'fr', 'JE NE ME RAPPELLE PAS / NE PEUX PAS DIVULGUER', 'ExpenseTracker'),

-- Hindi
('expenseTrackerTitle', 'hi', 'आपने गंतव्य में कितना खर्च किया या खर्च करने की योजना बनाई है?', 'ExpenseTracker'),
('expenseTrackerAccommodation', 'hi', 'आवास', 'ExpenseTracker'),
('expenseTrackerFoodandBeverage', 'hi', 'खाना और पेय', 'ExpenseTracker'),
('expenseTrackerShopping', 'hi', 'खरीदारी', 'ExpenseTracker'),
('expenseTrackerLocalTransport', 'hi', 'स्थानीय परिवहन', 'ExpenseTracker'),
('expenseTrackerTourismActivitiesEntertainment', 'hi', 'पर्यटन गतिविधियाँ/मनोरंजन', 'ExpenseTracker'),
('expenseTrackerMiscellaneous', 'hi', 'विविध', 'ExpenseTracker'),
('expenseTrackerSummaryTitle', 'hi', 'खर्च का सारांश', 'ExpenseTracker'),
('expenseTrackerTotalInCurrency', 'hi', 'कुल', 'ExpenseTracker'),
('expenseTrackerTotalInPHP', 'hi', 'PHP में कुल', 'ExpenseTracker'),
('expenseTrackerNextButton', 'hi', 'अगला', 'ExpenseTracker'),
('expenseTrackerForgetButton', 'hi', 'मुझे याद नहीं / खुलासा नहीं कर सकता', 'ExpenseTracker'),

-- Russian
('expenseTrackerTitle', 'ru', 'Сколько вы потратили или планируете потратить здесь, в пункте назначения?', 'ExpenseTracker'),
('expenseTrackerAccommodation', 'ru', 'Проживание', 'ExpenseTracker'),
('expenseTrackerFoodandBeverage', 'ru', 'Еда и напитки', 'ExpenseTracker'),
('expenseTrackerShopping', 'ru', 'Шопинг', 'ExpenseTracker'),
('expenseTrackerLocalTransport', 'ru', 'Местный транспорт', 'ExpenseTracker'),
('expenseTrackerTourismActivitiesEntertainment', 'ru', 'Туристические мероприятия/Развлечения', 'ExpenseTracker'),
('expenseTrackerMiscellaneous', 'ru', 'Разное', 'ExpenseTracker'),
('expenseTrackerSummaryTitle', 'ru', 'Сводка расходов', 'ExpenseTracker'),
('expenseTrackerTotalInCurrency', 'ru', 'Итого в', 'ExpenseTracker'),
('expenseTrackerTotalInPHP', 'ru', 'Итого в PHP', 'ExpenseTracker'),
('expenseTrackerNextButton', 'ru', 'Далее', 'ExpenseTracker'),
('expenseTrackerForgetButton', 'ru', 'НЕ ПОМНЮ / НЕ МОГУ РАСКРЫТЬ', 'ExpenseTracker');
