INSERT INTO localization00 (key, language_code, textcontent, component) VALUES
('feedbackFormTitle', 'en', 'Feedback Form', 'FeedbackForm'),
('feedbackFormPlaceholderDefault', 'en', 'Feel free to share any specific feedback', 'FeedbackForm'),
('feedbackFormPlaceholderDissatisfied', 'en', 'What went wrong? How can we improve?', 'FeedbackForm'),
('feedbackFormPlaceholderNeutral', 'en', 'What could have been better?', 'FeedbackForm'),
('feedbackFormPlaceholderSatisfied', 'en', 'What did you like? Any suggestions for improvement?', 'FeedbackForm'),
('feedbackFormPlaceholderVerySatisfied', 'en', 'What did you love? Any suggestions for improvement?', 'FeedbackForm'),
('feedbackFormOptionDissatisfied', 'en', 'Dissatisfied', 'FeedbackForm'),
('feedbackFormOptionNeutral', 'en', 'Neutral', 'FeedbackForm'),
('feedbackFormOptionSatisfied', 'en', 'Satisfied', 'FeedbackForm'),
('feedbackFormOptionVerySatisfied', 'en', 'Very satisfied', 'FeedbackForm'),
('feedbackFormNextButton', 'en', 'Next', 'FeedbackForm');


INSERT INTO localization00 (key, language_code, textcontent, component) VALUES
-- Korean (ko)
('feedbackFormTitle', 'ko', '피드백 양식', 'FeedbackForm'),
('feedbackFormPlaceholderDefault', 'ko', '구체적인 피드백을 자유롭게 공유해주세요.', 'FeedbackForm'),
('feedbackFormPlaceholderDissatisfied', 'ko', '무슨 일이 잘못되었나요? 어떻게 개선할 수 있을까요?', 'FeedbackForm'),
('feedbackFormPlaceholderNeutral', 'ko', '어떤 점이 더 나았으면 좋겠나요?', 'FeedbackForm'),
('feedbackFormPlaceholderSatisfied', 'ko', '어떤 점이 마음에 드셨나요? 개선을 위한 제안이 있나요?', 'FeedbackForm'),
('feedbackFormPlaceholderVerySatisfied', 'ko', '어떤 점이 좋으셨나요? 개선을 위한 제안이 있나요?', 'FeedbackForm'),
('feedbackFormOptionDissatisfied', 'ko', '불만족', 'FeedbackForm'),
('feedbackFormOptionNeutral', 'ko', '보통', 'FeedbackForm'),
('feedbackFormOptionSatisfied', 'ko', '만족', 'FeedbackForm'),
('feedbackFormOptionVerySatisfied', 'ko', '매우 만족', 'FeedbackForm'),
('feedbackFormNextButton', 'ko', '다음', 'FeedbackForm'),

-- Chinese (zh)
('feedbackFormTitle', 'zh', '反馈表单', 'FeedbackForm'),
('feedbackFormPlaceholderDefault', 'zh', '欢迎随时分享您的具体反馈', 'FeedbackForm'),
('feedbackFormPlaceholderDissatisfied', 'zh', '出了什么问题？我们该如何改进？', 'FeedbackForm'),
('feedbackFormPlaceholderNeutral', 'zh', '有什么可以做得更好的地方？', 'FeedbackForm'),
('feedbackFormPlaceholderSatisfied', 'zh', '您喜欢什么？有什么改进建议？', 'FeedbackForm'),
('feedbackFormPlaceholderVerySatisfied', 'zh', '您最喜欢什么？有什么改进建议？', 'FeedbackForm'),
('feedbackFormOptionDissatisfied', 'zh', '不满意', 'FeedbackForm'),
('feedbackFormOptionNeutral', 'zh', '一般', 'FeedbackForm'),
('feedbackFormOptionSatisfied', 'zh', '满意', 'FeedbackForm'),
('feedbackFormOptionVerySatisfied', 'zh', '非常满意', 'FeedbackForm'),
('feedbackFormNextButton', 'zh', '下一步', 'FeedbackForm'),

-- Japanese (ja)
('feedbackFormTitle', 'ja', 'フィードバックフォーム', 'FeedbackForm'),
('feedbackFormPlaceholderDefault', 'ja', '具体的なフィードバックを自由に共有してください。', 'FeedbackForm'),
('feedbackFormPlaceholderDissatisfied', 'ja', '何が問題でしたか？どう改善すれば良いですか？', 'FeedbackForm'),
('feedbackFormPlaceholderNeutral', 'ja', '何を改善できますか？', 'FeedbackForm'),
('feedbackFormPlaceholderSatisfied', 'ja', 'どの点が良かったですか？改善案はありますか？', 'FeedbackForm'),
('feedbackFormPlaceholderVerySatisfied', 'ja', 'どの点が素晴らしかったですか？改善案はありますか？', 'FeedbackForm'),
('feedbackFormOptionDissatisfied', 'ja', '不満足', 'FeedbackForm'),
('feedbackFormOptionNeutral', 'ja', '普通', 'FeedbackForm'),
('feedbackFormOptionSatisfied', 'ja', '満足', 'FeedbackForm'),
('feedbackFormOptionVerySatisfied', 'ja', '非常に満足', 'FeedbackForm'),
('feedbackFormNextButton', 'ja', '次へ', 'FeedbackForm'),

-- Spanish (es)
('feedbackFormTitle', 'es', 'Formulario de Retroalimentación', 'FeedbackForm'),
('feedbackFormPlaceholderDefault', 'es', 'Siéntase libre de compartir cualquier comentario específico', 'FeedbackForm'),
('feedbackFormPlaceholderDissatisfied', 'es', '¿Qué salió mal? ¿Cómo podemos mejorar?', 'FeedbackForm'),
('feedbackFormPlaceholderNeutral', 'es', '¿Qué podría haber sido mejor?', 'FeedbackForm'),
('feedbackFormPlaceholderSatisfied', 'es', '¿Qué le gustó? ¿Alguna sugerencia de mejora?', 'FeedbackForm'),
('feedbackFormPlaceholderVerySatisfied', 'es', '¿Qué le encantó? ¿Alguna sugerencia de mejora?', 'FeedbackForm'),
('feedbackFormOptionDissatisfied', 'es', 'Insatisfecho', 'FeedbackForm'),
('feedbackFormOptionNeutral', 'es', 'Neutral', 'FeedbackForm'),
('feedbackFormOptionSatisfied', 'es', 'Satisfecho', 'FeedbackForm'),
('feedbackFormOptionVerySatisfied', 'es', 'Muy satisfecho', 'FeedbackForm'),
('feedbackFormNextButton', 'es', 'Siguiente', 'FeedbackForm'),

-- French (fr)
('feedbackFormTitle', 'fr', 'Formulaire de Retour', 'FeedbackForm'),
('feedbackFormPlaceholderDefault', 'fr', 'N''hésitez pas à partager tout retour spécifique', 'FeedbackForm'),
('feedbackFormPlaceholderDissatisfied', 'fr', 'Qu''est-ce qui n''a pas fonctionné ? Comment pouvons-nous améliorer ?', 'FeedbackForm'),
('feedbackFormPlaceholderNeutral', 'fr', 'Qu''est-ce qui aurait pu être mieux ?', 'FeedbackForm'),
('feedbackFormPlaceholderSatisfied', 'fr', 'Qu''avez-vous aimé ? Des suggestions d''amélioration ?', 'FeedbackForm'),
('feedbackFormPlaceholderVerySatisfied', 'fr', 'Qu''avez-vous adoré ? Des suggestions d''amélioration ?', 'FeedbackForm'),
('feedbackFormOptionDissatisfied', 'fr', 'Insatisfait', 'FeedbackForm'),
('feedbackFormOptionNeutral', 'fr', 'Neutre', 'FeedbackForm'),
('feedbackFormOptionSatisfied', 'fr', 'Satisfait', 'FeedbackForm'),
('feedbackFormOptionVerySatisfied', 'fr', 'Très satisfait', 'FeedbackForm'),
('feedbackFormNextButton', 'fr', 'Suivant', 'FeedbackForm'),

-- Hindi (hi)
('feedbackFormTitle', 'hi', 'प्रतिक्रिया फ़ॉर्म', 'FeedbackForm'),
('feedbackFormPlaceholderDefault', 'hi', 'किसी भी विशेष प्रतिक्रिया को साझा करने के लिए स्वतंत्र महसूस करें।', 'FeedbackForm'),
('feedbackFormPlaceholderDissatisfied', 'hi', 'क्या गलत हुआ? हम कैसे सुधार कर सकते हैं?', 'FeedbackForm'),
('feedbackFormPlaceholderNeutral', 'hi', 'क्या बेहतर हो सकता था?', 'FeedbackForm'),
('feedbackFormPlaceholderSatisfied', 'hi', 'आपको क्या पसंद आया? कोई सुधार सुझाव?', 'FeedbackForm'),
('feedbackFormPlaceholderVerySatisfied', 'hi', 'आपको क्या बहुत अच्छा लगा? कोई सुधार सुझाव?', 'FeedbackForm'),
('feedbackFormOptionDissatisfied', 'hi', 'असंतुष्ट', 'FeedbackForm'),
('feedbackFormOptionNeutral', 'hi', 'तटस्थ', 'FeedbackForm'),
('feedbackFormOptionSatisfied', 'hi', 'संतुष्ट', 'FeedbackForm'),
('feedbackFormOptionVerySatisfied', 'hi', 'अत्यंत संतुष्ट', 'FeedbackForm'),
('feedbackFormNextButton', 'hi', 'अगला', 'FeedbackForm'),

-- Russian (ru)
('feedbackFormTitle', 'ru', 'Форма обратной связи', 'FeedbackForm'),
('feedbackFormPlaceholderDefault', 'ru', 'Не стесняйтесь поделиться своими конкретными отзывами', 'FeedbackForm'),
('feedbackFormPlaceholderDissatisfied', 'ru', 'Что пошло не так? Как мы можем улучшить?', 'FeedbackForm'),
('feedbackFormPlaceholderNeutral', 'ru', 'Что могло бы быть лучше?', 'FeedbackForm'),
('feedbackFormPlaceholderSatisfied', 'ru', 'Что вам понравилось? Есть ли предложения по улучшению?', 'FeedbackForm'),
('feedbackFormPlaceholderVerySatisfied', 'ru', 'Что вам очень понравилось? Есть ли предложения по улучшению?', 'FeedbackForm'),
('feedbackFormOptionDissatisfied', 'ru', 'Недоволен', 'FeedbackForm'),
('feedbackFormOptionNeutral', 'ru', 'Нейтрально', 'FeedbackForm'),
('feedbackFormOptionSatisfied', 'ru', 'Доволен', 'FeedbackForm'),
('feedbackFormOptionVerySatisfied', 'ru', 'Очень доволен', 'FeedbackForm'),
('feedbackFormNextButton', 'ru', 'Далее', 'FeedbackForm');
