INSERT INTO localization00 (key, language_code, textcontent, component) VALUES
('packTranspoQuestion', 'en', '(NOT PACKAGE TOUR)How much did you spend on transportation?', 'PackTranspo'),
('packTranspoQuestion', 'ko', '(패키지 여행 아님)교통비로 얼마를 썼나요?', 'PackTranspo'),
('packTranspoQuestion', 'zh', '(非套餐旅游)你在交通上花了多少钱？', 'PackTranspo'),
('packTranspoQuestion', 'ja', '(パッケージツアーではない)交通費はいくらでしたか？', 'PackTranspo'),
('packTranspoQuestion', 'es', '(NO TOUR PAQUETE)¿Cuánto gastaste en transporte?', 'PackTranspo'),
('packTranspoQuestion', 'fr', '(PAS DE FORFAIT)Combien avez-vous dépensé pour les transports ?', 'PackTranspo'),
('packTranspoQuestion', 'hi', '(पैकेज टूर नहीं)आपने परिवहन पर कितना खर्च किया?', 'PackTranspo'),
('packTranspoQuestion', 'ru', '(НЕ ПАКЕТНЫЙ ТУР)Сколько вы потратили на транспорт?', 'PackTranspo'),

('packTranspoInputLabel', 'en', 'Enter Amount and Select Currency', 'PackTranspo'),
('packTranspoInputLabel', 'ko', '금액 입력 및 통화 선택', 'PackTranspo'),
('packTranspoInputLabel', 'zh', '输入金额并选择货币', 'PackTranspo'),
('packTranspoInputLabel', 'ja', '金額を入力して通貨を選択', 'PackTranspo'),
('packTranspoInputLabel', 'es', 'Ingrese el monto y seleccione la moneda', 'PackTranspo'),
('packTranspoInputLabel', 'fr', 'Entrez le montant et sélectionnez la devise', 'PackTranspo'),
('packTranspoInputLabel', 'hi', 'राशि दर्ज करें और मुद्रा चुनें', 'PackTranspo'),
('packTranspoInputLabel', 'ru', 'Введите сумму и выберите валюту', 'PackTranspo'),

('packTranspoInputPlaceholder', 'en', 'Tour Package Price', 'PackTranspo'),
('packTranspoInputPlaceholder', 'ko', '패키지 여행 가격', 'PackTranspo'),
('packTranspoInputPlaceholder', 'zh', '旅游套餐价格', 'PackTranspo'),
('packTranspoInputPlaceholder', 'ja', 'ツアーパッケージの価格', 'PackTranspo'),
('packTranspoInputPlaceholder', 'es', 'Precio del paquete turístico', 'PackTranspo'),
('packTranspoInputPlaceholder', 'fr', 'Prix du forfait touristique', 'PackTranspo'),
('packTranspoInputPlaceholder', 'hi', 'टूर पैकेज की कीमत', 'PackTranspo'),
('packTranspoInputPlaceholder', 'ru', 'Цена турпакета', 'PackTranspo'),

('packTranspoCurrencyUSD', 'en', 'USD - US Dollar', 'PackTranspo'),
('packTranspoCurrencyUSD', 'ko', 'USD - 미국 달러', 'PackTranspo'),
('packTranspoCurrencyUSD', 'zh', 'USD - 美元', 'PackTranspo'),
('packTranspoCurrencyUSD', 'ja', 'USD - 米ドル', 'PackTranspo'),
('packTranspoCurrencyUSD', 'es', 'USD - Dólar estadounidense', 'PackTranspo'),
('packTranspoCurrencyUSD', 'fr', 'USD - Dollar américain', 'PackTranspo'),
('packTranspoCurrencyUSD', 'hi', 'USD - अमेरिकी डॉलर', 'PackTranspo'),
('packTranspoCurrencyUSD', 'ru', 'USD - Доллар США', 'PackTranspo'),

('packTranspoCurrencyEUR', 'en', 'EUR - Euro', 'PackTranspo'),
('packTranspoCurrencyEUR', 'ko', 'EUR - 유로', 'PackTranspo'),
('packTranspoCurrencyEUR', 'zh', 'EUR - 欧元', 'PackTranspo'),
('packTranspoCurrencyEUR', 'ja', 'EUR - ユーロ', 'PackTranspo'),
('packTranspoCurrencyEUR', 'es', 'EUR - Euro', 'PackTranspo'),
('packTranspoCurrencyEUR', 'fr', 'EUR - Euro', 'PackTranspo'),
('packTranspoCurrencyEUR', 'hi', 'EUR - यूरो', 'PackTranspo'),
('packTranspoCurrencyEUR', 'ru', 'EUR - Евро', 'PackTranspo'),

('packTranspoCurrencyJPY', 'en', 'JPY - Japanese Yen', 'PackTranspo'),
('packTranspoCurrencyJPY', 'ko', 'JPY - 일본 엔', 'PackTranspo'),
('packTranspoCurrencyJPY', 'zh', 'JPY - 日元', 'PackTranspo'),
('packTranspoCurrencyJPY', 'ja', 'JPY - 日本円', 'PackTranspo'),
('packTranspoCurrencyJPY', 'es', 'JPY - Yen japonés', 'PackTranspo'),
('packTranspoCurrencyJPY', 'fr', 'JPY - Yen japonais', 'PackTranspo'),
('packTranspoCurrencyJPY', 'hi', 'JPY - जापानी येन', 'PackTranspo'),
('packTranspoCurrencyJPY', 'ru', 'JPY - Японская иена', 'PackTranspo'),

('packTranspoCurrencyPHP', 'en', 'PHP - Philippine Peso', 'PackTranspo'),
('packTranspoCurrencyPHP', 'ko', 'PHP - 필리핀 페소', 'PackTranspo'),
('packTranspoCurrencyPHP', 'zh', 'PHP - 菲律宾比索', 'PackTranspo'),
('packTranspoCurrencyPHP', 'ja', 'PHP - 필리핀 페소', 'PackTranspo'),
('packTranspoCurrencyPHP', 'es', 'PHP - Peso filipino', 'PackTranspo'),
('packTranspoCurrencyPHP', 'fr', 'PHP - Peso philippin', 'PackTranspo'),
('packTranspoCurrencyPHP', 'hi', 'PHP - फिलिपिनो पेसो', 'PackTranspo'),
('packTranspoCurrencyPHP', 'ru', 'PHP - Филиппинское песо', 'PackTranspo'),

('packTranspoCurrencyCNY', 'en', 'CNY - Chinese Yuan', 'PackTranspo'),
('packTranspoCurrencyCNY', 'ko', 'CNY - 중국 위안', 'PackTranspo'),
('packTranspoCurrencyCNY', 'zh', 'CNY - 人民币', 'PackTranspo'),
('packTranspoCurrencyCNY', 'ja', 'CNY - 人民元', 'PackTranspo'),
('packTranspoCurrencyCNY', 'es', 'CNY - Yuan chino', 'PackTranspo'),
('packTranspoCurrencyCNY', 'fr', 'CNY - Yuan chinois', 'PackTranspo'),
('packTranspoCurrencyCNY', 'hi', 'CNY - चीनी युआन', 'PackTranspo'),
('packTranspoCurrencyCNY', 'ru', 'CNY - Китайский юань', 'PackTranspo'),

('packTranspoCurrencyINR', 'en', 'INR - Indian Rupee', 'PackTranspo'),
('packTranspoCurrencyINR', 'ko', 'INR - 인도 루피', 'PackTranspo'),
('packTranspoCurrencyINR', 'zh', 'INR - 印度卢比', 'PackTranspo'),
('packTranspoCurrencyINR', 'ja', 'INR - インドルピー', 'PackTranspo'),
('packTranspoCurrencyINR', 'es', 'INR - Rupia india', 'PackTranspo'),
('packTranspoCurrencyINR', 'fr', 'INR - Roupie indienne', 'PackTranspo'),
('packTranspoCurrencyINR', 'hi', 'INR - भारतीय रुपया', 'PackTranspo'),
('packTranspoCurrencyINR', 'ru', 'INR - Индийская рупия', 'PackTranspo'),

('packTranspoCurrencyRUB', 'en', 'RUB - Russian Ruble', 'PackTranspo'),
('packTranspoCurrencyRUB', 'ko', 'RUB - 러시아 루블', 'PackTranspo'),
('packTranspoCurrencyRUB', 'zh', 'RUB - 俄罗斯卢布', 'PackTranspo'),
('packTranspoCurrencyRUB', 'ja', 'RUB - ロシアルーブル', 'PackTranspo'),
('packTranspoCurrencyRUB', 'es', 'RUB - Rublo ruso', 'PackTranspo'),
('packTranspoCurrencyRUB', 'fr', 'RUB - Rouble russe', 'PackTranspo'),
('packTranspoCurrencyRUB', 'hi', 'RUB - रूसी रूबल', 'PackTranspo'),
('packTranspoCurrencyRUB', 'ru', 'RUB - Российский рубль', 'PackTranspo'),

('packTranspoCurrencyKRW', 'en', 'KRW - Korean Won', 'PackTranspo'),
('packTranspoCurrencyKRW', 'ko', 'KRW - 원', 'PackTranspo'),
('packTranspoCurrencyKRW', 'zh', 'KRW - 韩元', 'PackTranspo'),
('packTranspoCurrencyKRW', 'ja', 'KRW - 韓国ウォン', 'PackTranspo'),
('packTranspoCurrencyKRW', 'es', 'KRW - Won coreano', 'PackTranspo'),
('packTranspoCurrencyKRW', 'fr', 'KRW - Won coréen', 'PackTranspo'),
('packTranspoCurrencyKRW', 'hi', 'KRW - कोरियाई वोन', 'PackTranspo'),
('packTranspoCurrencyKRW', 'ru', 'KRW - Корейская вона', 'PackTranspo'),

('packTranspoCurrencyFRF', 'en', 'FRF - French Franc', 'PackTranspo'),
('packTranspoCurrencyFRF', 'ko', 'FRF - 프랑스 프랑', 'PackTranspo'),
('packTranspoCurrencyFRF', 'zh', 'FRF - 法国法郎', 'PackTranspo'),
('packTranspoCurrencyFRF', 'ja', 'FRF - フランス・フラン', 'PackTranspo'),
('packTranspoCurrencyFRF', 'es', 'FRF - Franco francés', 'PackTranspo'),
('packTranspoCurrencyFRF', 'fr', 'FRF - Franc français', 'PackTranspo'),
('packTranspoCurrencyFRF', 'hi', 'FRF - फ्रांसीसी फ्रैंक', 'PackTranspo'),
('packTranspoCurrencyFRF', 'ru', 'FRF - Франк французский', 'PackTranspo'),

('packTranspoCurrencyESP', 'en', 'ESP - Spanish Peseta', 'PackTranspo'),
('packTranspoCurrencyESP', 'ko', 'ESP - 스페인 페세타', 'PackTranspo'),
('packTranspoCurrencyESP', 'zh', 'ESP - 西班牙比塞塔', 'PackTranspo'),
('packTranspoCurrencyESP', 'ja', 'ESP - スペイン・ペセタ', 'PackTranspo'),
('packTranspoCurrencyESP', 'es', 'ESP - Peseta española', 'PackTranspo'),
('packTranspoCurrencyESP', 'fr', 'ESP - Peseta espagnole', 'PackTranspo'),
('packTranspoCurrencyESP', 'hi', 'ESP - स्पेनिश पेसाटा', 'PackTranspo'),
('packTranspoCurrencyESP', 'ru', 'ESP - Испанская песета', 'PackTranspo'),

('packTranspoConversionResult', 'en', 'is approximately', 'PackTranspo'),
('packTranspoConversionResult', 'ko', '대략', 'PackTranspo'),
('packTranspoConversionResult', 'zh', '大约是', 'PackTranspo'),
('packTranspoConversionResult', 'ja', '約', 'PackTranspo'),
('packTranspoConversionResult', 'es', 'es aproximadamente', 'PackTranspo'),
('packTranspoConversionResult', 'fr', 'est environ', 'PackTranspo'),
('packTranspoConversionResult', 'hi', 'लगभग है', 'PackTranspo'),
('packTranspoConversionResult', 'ru', 'примерно', 'PackTranspo'),

('packTranspoNextButton', 'en', 'Next', 'PackTranspo'),
('packTranspoNextButton', 'ko', '다음', 'PackTranspo'),
('packTranspoNextButton', 'zh', '下一步', 'PackTranspo'),
('packTranspoNextButton', 'ja', '次へ', 'PackTranspo'),
('packTranspoNextButton', 'es', 'Siguiente', 'PackTranspo'),
('packTranspoNextButton', 'fr', 'Suivant', 'PackTranspo'),
('packTranspoNextButton', 'hi', 'अगला', 'PackTranspo'),
('packTranspoNextButton', 'ru', 'Далее', 'PackTranspo'),

('packTranspoAlertMessage', 'en', 'You paid', 'PackTranspo'),
('packTranspoAlertMessage', 'ko', '당신은 지불했습니다', 'PackTranspo'),
('packTranspoAlertMessage', 'zh', '你支付了', 'PackTranspo'),
('packTranspoAlertMessage', 'ja', '支払いました', 'PackTranspo'),
('packTranspoAlertMessage', 'es', 'Usted pagó', 'PackTranspo'),
('packTranspoAlertMessage', 'fr', 'Vous avez payé', 'PackTranspo'),
('packTranspoAlertMessage', 'hi', 'आपने भुगतान किया', 'PackTranspo'),
('packTranspoAlertMessage', 'ru', 'Вы заплатили', 'PackTranspo'),

('packTranspoAlertConvertedMessage', 'en', 'which is approximately', 'PackTranspo'),
('packTranspoAlertConvertedMessage', 'ko', '대략', 'PackTranspo'),
('packTranspoAlertConvertedMessage', 'zh', '大约是', 'PackTranspo'),
('packTranspoAlertConvertedMessage', 'ja', '約', 'PackTranspo'),
('packTranspoAlertConvertedMessage', 'es', 'que es aproximadamente', 'PackTranspo'),
('packTranspoAlertConvertedMessage', 'fr', 'ce qui est environ', 'PackTranspo'),
('packTranspoAlertConvertedMessage', 'hi', 'जो लगभग है', 'PackTranspo'),
('packTranspoAlertConvertedMessage', 'ru', 'что примерно', 'PackTranspo');
