INSERT INTO localization00 (key, language_code, textcontent, component) VALUES
('packagePaidQuestion', 'en', 'How much did you pay for your package tour?', 'PackagePaid'),
('packagePaidInputLabel', 'en', 'Enter Amount and Select Currency', 'PackagePaid'),
('packagePaidInputPlaceholder', 'en', 'Tour Package Price', 'PackagePaid'),
('packagePaidCurrencyUSD', 'en', 'USD - US Dollar', 'PackagePaid'),
('packagePaidCurrencyEUR', 'en', 'EUR - Euro', 'PackagePaid'),
('packagePaidCurrencyJPY', 'en', 'JPY - Japanese Yen', 'PackagePaid'),
('packagePaidCurrencyPHP', 'en', 'PHP - Philippine Peso', 'PackagePaid'),
('packagePaidCurrencyCNY', 'en', 'CNY - Chinese Yuan', 'PackagePaid'),
('packagePaidCurrencyINR', 'en', 'INR - Indian Rupee', 'PackagePaid'),
('packagePaidCurrencyRUB', 'en', 'RUB - Russian Ruble', 'PackagePaid'),
('packagePaidCurrencyKRW', 'en', 'KRW - Korean Won', 'PackagePaid'),
('packagePaidCurrencyFRF', 'en', 'FRF - French Franc', 'PackagePaid'),
('packagePaidCurrencyESP', 'en', 'ESP - Spanish Peseta', 'PackagePaid'),
('packagePaidConversionResult', 'en', '', 'PackagePaid'),
('packagePaidConversionResultApprox', 'en', 'is approximately', 'PackagePaid'),
('packagePaidNextButton', 'en', 'Next', 'PackagePaid'),

-- Korean translations
('packagePaidQuestion', 'ko', '패키지 여행에 대해 얼마나 지불하셨나요?', 'PackagePaid'),
('packagePaidInputLabel', 'ko', '금액을 입력하고 통화를 선택하세요', 'PackagePaid'),
('packagePaidInputPlaceholder', 'ko', '투어 패키지 가격', 'PackagePaid'),
('packagePaidCurrencyUSD', 'ko', 'USD - 미국 달러', 'PackagePaid'),
('packagePaidCurrencyEUR', 'ko', 'EUR - 유로', 'PackagePaid'),
('packagePaidCurrencyJPY', 'ko', 'JPY - 일본 엔', 'PackagePaid'),
('packagePaidCurrencyPHP', 'ko', 'PHP - 필리핀 페소', 'PackagePaid'),
('packagePaidCurrencyCNY', 'ko', 'CNY - 중국 위안', 'PackagePaid'),
('packagePaidCurrencyINR', 'ko', 'INR - 인도 루피', 'PackagePaid'),
('packagePaidCurrencyRUB', 'ko', 'RUB - 러시아 루블', 'PackagePaid'),
('packagePaidCurrencyKRW', 'ko', 'KRW - 한국 원', 'PackagePaid'),
('packagePaidCurrencyFRF', 'ko', 'FRF - 프랑스 프랑', 'PackagePaid'),
('packagePaidCurrencyESP', 'ko', 'ESP - 스페인 페세타', 'PackagePaid'),
('packagePaidConversionResult', 'ko', '', 'PackagePaid'),
('packagePaidConversionResultApprox', 'ko', '대략', 'PackagePaid'),
('packagePaidNextButton', 'ko', '다음', 'PackagePaid'),

-- Chinese translations
('packagePaidQuestion', 'zh', '您为您的包价旅游支付了多少？', 'PackagePaid'),
('packagePaidInputLabel', 'zh', '请输入金额并选择货币', 'PackagePaid'),
('packagePaidInputPlaceholder', 'zh', '旅游包价', 'PackagePaid'),
('packagePaidCurrencyUSD', 'zh', 'USD - 美元', 'PackagePaid'),
('packagePaidCurrencyEUR', 'zh', 'EUR - 欧元', 'PackagePaid'),
('packagePaidCurrencyJPY', 'zh', 'JPY - 日元', 'PackagePaid'),
('packagePaidCurrencyPHP', 'zh', 'PHP - 菲律宾比索', 'PackagePaid'),
('packagePaidCurrencyCNY', 'zh', 'CNY - 人民币', 'PackagePaid'),
('packagePaidCurrencyINR', 'zh', 'INR - 印度卢比', 'PackagePaid'),
('packagePaidCurrencyRUB', 'zh', 'RUB - 俄罗斯卢布', 'PackagePaid'),
('packagePaidCurrencyKRW', 'zh', 'KRW - 韩元', 'PackagePaid'),
('packagePaidCurrencyFRF', 'zh', 'FRF - 法国法郎', 'PackagePaid'),
('packagePaidCurrencyESP', 'zh', 'ESP - 西班牙比塞塔', 'PackagePaid'),
('packagePaidConversionResult', 'zh', '', 'PackagePaid'),
('packagePaidConversionResultApprox', 'zh', '大约', 'PackagePaid'),
('packagePaidNextButton', 'zh', '下一步', 'PackagePaid'),

-- Japanese translations
('packagePaidQuestion', 'ja', 'パッケージツアーにいくら支払いましたか？', 'PackagePaid'),
('packagePaidInputLabel', 'ja', '金額を入力し、通貨を選択してください', 'PackagePaid'),
('packagePaidInputPlaceholder', 'ja', 'ツアーパッケージの価格', 'PackagePaid'),
('packagePaidCurrencyUSD', 'ja', 'USD - 米ドル', 'PackagePaid'),
('packagePaidCurrencyEUR', 'ja', 'EUR - ユーロ', 'PackagePaid'),
('packagePaidCurrencyJPY', 'ja', 'JPY - 日本円', 'PackagePaid'),
('packagePaidCurrencyPHP', 'ja', 'PHP - フィリピンペソ', 'PackagePaid'),
('packagePaidCurrencyCNY', 'ja', 'CNY - 人民元', 'PackagePaid'),
('packagePaidCurrencyINR', 'ja', 'INR - インドルピー', 'PackagePaid'),
('packagePaidCurrencyRUB', 'ja', 'RUB - ロシアルーブル', 'PackagePaid'),
('packagePaidCurrencyKRW', 'ja', 'KRW - 韓国ウォン', 'PackagePaid'),
('packagePaidCurrencyFRF', 'ja', 'FRF - フランスフラン', 'PackagePaid'),
('packagePaidCurrencyESP', 'ja', 'ESP - スペインペセタ', 'PackagePaid'),
('packagePaidConversionResult', 'ja', '', 'PackagePaid'),
('packagePaidConversionResultApprox', 'ja', 'おおよそ', 'PackagePaid'),
('packagePaidNextButton', 'ja', '次へ', 'PackagePaid'),

-- Spanish translations
('packagePaidQuestion', 'es', '¿Cuánto pagaste por tu tour de paquete?', 'PackagePaid'),
('packagePaidInputLabel', 'es', 'Ingresa el monto y selecciona la moneda', 'PackagePaid'),
('packagePaidInputPlaceholder', 'es', 'Precio del paquete turístico', 'PackagePaid'),
('packagePaidCurrencyUSD', 'es', 'USD - Dólar estadounidense', 'PackagePaid'),
('packagePaidCurrencyEUR', 'es', 'EUR - Euro', 'PackagePaid'),
('packagePaidCurrencyJPY', 'es', 'JPY - Yen japonés', 'PackagePaid'),
('packagePaidCurrencyPHP', 'es', 'PHP - Peso filipino', 'PackagePaid'),
('packagePaidCurrencyCNY', 'es', 'CNY - Yuan chino', 'PackagePaid'),
('packagePaidCurrencyINR', 'es', 'INR - Rupia india', 'PackagePaid'),
('packagePaidCurrencyRUB', 'es', 'RUB - Rublo ruso', 'PackagePaid'),
('packagePaidCurrencyKRW', 'es', 'KRW - Won surcoreano', 'PackagePaid'),
('packagePaidCurrencyFRF', 'es', 'FRF - Franco francés', 'PackagePaid'),
('packagePaidCurrencyESP', 'es', 'ESP - Peseta española', 'PackagePaid'),
('packagePaidConversionResult', 'es', '', 'PackagePaid'),
('packagePaidConversionResultApprox', 'es', 'es aproximadamente', 'PackagePaid'),
('packagePaidNextButton', 'es', 'Siguiente', 'PackagePaid'),

-- French translations
('packagePaidQuestion', 'fr', 'Combien avez-vous payé pour votre voyage organisé ?', 'PackagePaid'),
('packagePaidInputLabel', 'fr', 'Entrez le montant et sélectionnez la devise', 'PackagePaid'),
('packagePaidInputPlaceholder', 'fr', 'Prix du forfait touristique', 'PackagePaid'),
('packagePaidCurrencyUSD', 'fr', 'USD - Dollar américain', 'PackagePaid'),
('packagePaidCurrencyEUR', 'fr', 'EUR - Euro', 'PackagePaid'),
('packagePaidCurrencyJPY', 'fr', 'JPY - Yen japonais', 'PackagePaid'),
('packagePaidCurrencyPHP', 'fr', 'PHP - Peso philippin', 'PackagePaid'),
('packagePaidCurrencyCNY', 'fr', 'CNY - Yuan chinois', 'PackagePaid'),
('packagePaidCurrencyINR', 'fr', 'INR - Roupie indienne', 'PackagePaid'),
('packagePaidCurrencyRUB', 'fr', 'RUB - Rouble russe', 'PackagePaid'),
('packagePaidCurrencyKRW', 'fr', 'KRW - Won sud-coréen', 'PackagePaid'),
('packagePaidCurrencyFRF', 'fr', 'FRF - Franc français', 'PackagePaid'),
('packagePaidCurrencyESP', 'fr', 'ESP - Peseta espagnole', 'PackagePaid'),
('packagePaidConversionResult', 'fr', '', 'PackagePaid'),
('packagePaidConversionResultApprox', 'fr', 'est environ', 'PackagePaid'),
('packagePaidNextButton', 'fr', 'Suivant', 'PackagePaid'),

-- Hindi translations
('packagePaidQuestion', 'hi', 'आपने अपनी पैकेज टूर के लिए कितना भुगतान किया?', 'PackagePaid'),
('packagePaidInputLabel', 'hi', 'राशि दर्ज करें और मुद्रा का चयन करें', 'PackagePaid'),
('packagePaidInputPlaceholder', 'hi', 'टूर पैकेज की कीमत', 'PackagePaid'),
('packagePaidCurrencyUSD', 'hi', 'USD - अमेरिकी डॉलर', 'PackagePaid'),
('packagePaidCurrencyEUR', 'hi', 'EUR - यूरो', 'PackagePaid'),
('packagePaidCurrencyJPY', 'hi', 'JPY - जापानी येन', 'PackagePaid'),
('packagePaidCurrencyPHP', 'hi', 'PHP - फिलीपिन पेसो', 'PackagePaid'),
('packagePaidCurrencyCNY', 'hi', 'CNY - चीनी युआन', 'PackagePaid'),
('packagePaidCurrencyINR', 'hi', 'INR - भारतीय रुपया', 'PackagePaid'),
('packagePaidCurrencyRUB', 'hi', 'RUB - रूसी रूबल', 'PackagePaid'),
('packagePaidCurrencyKRW', 'hi', 'KRW - कोरियाई वोन', 'PackagePaid'),
('packagePaidCurrencyFRF', 'hi', 'FRF - फ्रांसीसी फ्रैंक', 'PackagePaid'),
('packagePaidCurrencyESP', 'hi', 'ESP - स्पेनिश पेसिटा', 'PackagePaid'),
('packagePaidConversionResult', 'hi', '', 'PackagePaid'),
('packagePaidConversionResultApprox', 'hi', 'लगभग', 'PackagePaid'),
('packagePaidNextButton', 'hi', 'अगला', 'PackagePaid'),

-- Russian translations
('packagePaidQuestion', 'ru', 'Сколько вы заплатили за ваш туристический пакет?', 'PackagePaid'),
('packagePaidInputLabel', 'ru', 'Введите сумму и выберите валюту', 'PackagePaid'),
('packagePaidInputPlaceholder', 'ru', 'Цена туристического пакета', 'PackagePaid'),
('packagePaidCurrencyUSD', 'ru', 'USD - Американский доллар', 'PackagePaid'),
('packagePaidCurrencyEUR', 'ru', 'EUR - Евро', 'PackagePaid'),
('packagePaidCurrencyJPY', 'ru', 'JPY - Японская иена', 'PackagePaid'),
('packagePaidCurrencyPHP', 'ru', 'PHP - Филиппинское песо', 'PackagePaid'),
('packagePaidCurrencyCNY', 'ru', 'CNY - Китайский юань', 'PackagePaid'),
('packagePaidCurrencyINR', 'ru', 'INR - Индийская рупия', 'PackagePaid'),
('packagePaidCurrencyRUB', 'ru', 'RUB - Российский рубль', 'PackagePaid'),
('packagePaidCurrencyKRW', 'ru', 'KRW - Корейская вона', 'PackagePaid'),
('packagePaidCurrencyFRF', 'ru', 'FRF - Французский франк', 'PackagePaid'),
('packagePaidCurrencyESP', 'ru', 'ESP - Испанская песета', 'PackagePaid'),
('packagePaidConversionResult', 'ru', '', 'PackagePaid'),
('packagePaidConversionResultApprox', 'ru', 'приблизительно', 'PackagePaid'),
('packagePaidNextButton', 'ru', 'Далее', 'PackagePaid');
