INSERT INTO localization00 (key, language_code, textcontent, component) VALUES
('ageLabel', 'en', 'a. Age:', 'PProfile1'),
('nationalityLabel', 'en', 'b. Nationality:', 'PProfile1'),
('sexLabel', 'en', 'c. Sex:', 'PProfile1'),
('civilStatusLabel', 'en', 'd. Civil Status:', 'PProfile1'),
('occupationLabel', 'en', 'e. Occupation:', 'PProfile1'),
('incomeLabel', 'en', 'f. What is your annual gross income? :', 'PProfile1'),
('currencyLabel', 'en', 'Currency:', 'PProfile1'),
('convertedIncomeLabel', 'en', 'Converted Income (PHP):', 'PProfile1'),
('nextButton', 'en', 'Next', 'PProfile1'),
('nationalityAmerican', 'en', 'American', 'PProfile1'),
('nationalityFilipino', 'en', 'Filipino', 'PProfile1'),
('sexMale', 'en', 'Male', 'PProfile1'),
('sexFemale', 'en', 'Female', 'PProfile1'),
('civilStatusSingle', 'en', 'Single', 'PProfile1'),
('civilStatusMarried', 'en', 'Married/Common Law', 'PProfile1'),
('invalidIncome', 'en', 'Invalid income', 'PProfile1'),

-- Korean Localizations
('ageLabel', 'ko', 'a. 나이:', 'PProfile1'),
('nationalityLabel', 'ko', 'b. 국적:', 'PProfile1'),
('sexLabel', 'ko', 'c. 성별:', 'PProfile1'),
('civilStatusLabel', 'ko', 'd. 결혼 상태:', 'PProfile1'),
('occupationLabel', 'ko', 'e. 직업:', 'PProfile1'),
('incomeLabel', 'ko', 'f. 연간 총 수입은 얼마인가요?:', 'PProfile1'),
('currencyLabel', 'ko', '통화:', 'PProfile1'),
('convertedIncomeLabel', 'ko', '환산된 수입 (PHP):', 'PProfile1'),
('nextButton', 'ko', '다음', 'PProfile1'),
('nationalityAmerican', 'ko', '미국인', 'PProfile1'),
('nationalityFilipino', 'ko', '필리핀인', 'PProfile1'),
('sexMale', 'ko', '남성', 'PProfile1'),
('sexFemale', 'ko', '여성', 'PProfile1'),
('civilStatusSingle', 'ko', '독신', 'PProfile1'),
('civilStatusMarried', 'ko', '결혼/동거', 'PProfile1'),
('invalidIncome', 'ko', '잘못된 수입', 'PProfile1'),

-- Chinese Localizations (Simplified)
('ageLabel', 'zh', 'a. 年龄:', 'PProfile1'),
('nationalityLabel', 'zh', 'b. 国籍:', 'PProfile1'),
('sexLabel', 'zh', 'c. 性别:', 'PProfile1'),
('civilStatusLabel', 'zh', 'd. 婚姻状况:', 'PProfile1'),
('occupationLabel', 'zh', 'e. 职业:', 'PProfile1'),
('incomeLabel', 'zh', 'f. 您的年收入是多少?:', 'PProfile1'),
('currencyLabel', 'zh', '货币:', 'PProfile1'),
('convertedIncomeLabel', 'zh', '转换后的收入 (PHP):', 'PProfile1'),
('nextButton', 'zh', '下一步', 'PProfile1'),
('nationalityAmerican', 'zh', '美国人', 'PProfile1'),
('nationalityFilipino', 'zh', '菲律宾人', 'PProfile1'),
('sexMale', 'zh', '男', 'PProfile1'),
('sexFemale', 'zh', '女', 'PProfile1'),
('civilStatusSingle', 'zh', '单身', 'PProfile1'),
('civilStatusMarried', 'zh', '已婚/同居', 'PProfile1'),
('invalidIncome', 'zh', '无效收入', 'PProfile1'),

-- Japanese Localizations
('ageLabel', 'ja', 'a. 年齢:', 'PProfile1'),
('nationalityLabel', 'ja', 'b. 国籍:', 'PProfile1'),
('sexLabel', 'ja', 'c. 性別:', 'PProfile1'),
('civilStatusLabel', 'ja', 'd. 婚姻状況:', 'PProfile1'),
('occupationLabel', 'ja', 'e. 職業:', 'PProfile1'),
('incomeLabel', 'ja', 'f. あなたの年間総収入は何ですか?:', 'PProfile1'),
('currencyLabel', 'ja', '通貨:', 'PProfile1'),
('convertedIncomeLabel', 'ja', '変換された収入 (PHP):', 'PProfile1'),
('nextButton', 'ja', '次へ', 'PProfile1'),
('nationalityAmerican', 'ja', 'アメリカ人', 'PProfile1'),
('nationalityFilipino', 'ja', 'フィリピン人', 'PProfile1'),
('sexMale', 'ja', '男性', 'PProfile1'),
('sexFemale', 'ja', '女性', 'PProfile1'),
('civilStatusSingle', 'ja', '独身', 'PProfile1'),
('civilStatusMarried', 'ja', '結婚/同居', 'PProfile1'),
('invalidIncome', 'ja', '無効な収入', 'PProfile1'),

-- Spanish Localizations
('ageLabel', 'es', 'a. Edad:', 'PProfile1'),
('nationalityLabel', 'es', 'b. Nacionalidad:', 'PProfile1'),
('sexLabel', 'es', 'c. Sexo:', 'PProfile1'),
('civilStatusLabel', 'es', 'd. Estado civil:', 'PProfile1'),
('occupationLabel', 'es', 'e. Ocupación:', 'PProfile1'),
('incomeLabel', 'es', 'f. ¿Cuál es tu ingreso bruto anual?:', 'PProfile1'),
('currencyLabel', 'es', 'Moneda:', 'PProfile1'),
('convertedIncomeLabel', 'es', 'Ingreso convertido (PHP):', 'PProfile1'),
('nextButton', 'es', 'Siguiente', 'PProfile1'),
('nationalityAmerican', 'es', 'Estadounidense', 'PProfile1'),
('nationalityFilipino', 'es', 'Filipino', 'PProfile1'),
('sexMale', 'es', 'Masculino', 'PProfile1'),
('sexFemale', 'es', 'Femenino', 'PProfile1'),
('civilStatusSingle', 'es', 'Soltero', 'PProfile1'),
('civilStatusMarried', 'es', 'Casado/Conviviente', 'PProfile1'),
('invalidIncome', 'es', 'Ingreso inválido', 'PProfile1'),

-- French Localizations
('ageLabel', 'fr', 'a. Âge:', 'PProfile1'),
('nationalityLabel', 'fr', 'b. Nationalité:', 'PProfile1'),
('sexLabel', 'fr', 'c. Sexe:', 'PProfile1'),
('civilStatusLabel', 'fr', 'd. État civil:', 'PProfile1'),
('occupationLabel', 'fr', 'e. Profession:', 'PProfile1'),
('incomeLabel', 'fr', 'f. Quel est votre revenu brut annuel?:', 'PProfile1'),
('currencyLabel', 'fr', 'Devise:', 'PProfile1'),
('convertedIncomeLabel', 'fr', 'Revenu converti (PHP):', 'PProfile1'),
('nextButton', 'fr', 'Suivant', 'PProfile1'),
('nationalityAmerican', 'fr', 'Américain', 'PProfile1'),
('nationalityFilipino', 'fr', 'Philippin', 'PProfile1'),
('sexMale', 'fr', 'Homme', 'PProfile1'),
('sexFemale', 'fr', 'Femme', 'PProfile1'),
('civilStatusSingle', 'fr', 'Célibataire', 'PProfile1'),
('civilStatusMarried', 'fr', 'Marié/Union libre', 'PProfile1'),
('invalidIncome', 'fr', 'Revenu invalide', 'PProfile1'),

-- Hindi Localizations
('ageLabel', 'hi', 'a. उम्र:', 'PProfile1'),
('nationalityLabel', 'hi', 'b. राष्ट्रीयता:', 'PProfile1'),
('sexLabel', 'hi', 'c. लिंग:', 'PProfile1'),
('civilStatusLabel', 'hi', 'd. वैवाहिक स्थिति:', 'PProfile1'),
('occupationLabel', 'hi', 'e. पेशा:', 'PProfile1'),
('incomeLabel', 'hi', 'f. आपका वार्षिक सकल आय क्या है?:', 'PProfile1'),
('currencyLabel', 'hi', 'मुद्रा:', 'PProfile1'),
('convertedIncomeLabel', 'hi', 'परिवर्तित आय (PHP):', 'PProfile1'),
('nextButton', 'hi', 'अगला', 'PProfile1'),
('nationalityAmerican', 'hi', 'अमेरिकी', 'PProfile1'),
('nationalityFilipino', 'hi', 'फिलीपिनो', 'PProfile1'),
('sexMale', 'hi', 'पुरुष', 'PProfile1'),
('sexFemale', 'hi', 'महिला', 'PProfile1'),
('civilStatusSingle', 'hi', 'अविवाहित', 'PProfile1'),
('civilStatusMarried', 'hi', 'विवाहित/सामान्य कानून', 'PProfile1'),
('invalidIncome', 'hi', 'अमान्य आय', 'PProfile1'),

-- Russian Localizations
('ageLabel', 'ru', 'a. Возраст:', 'PProfile1'),
('nationalityLabel', 'ru', 'b. Национальность:', 'PProfile1'),
('sexLabel', 'ru', 'c. Пол:', 'PProfile1'),
('civilStatusLabel', 'ru', 'd. Семейное положение:', 'PProfile1'),
('occupationLabel', 'ru', 'e. Профессия:', 'PProfile1'),
('incomeLabel', 'ru', 'f. Какой ваш ежегодный валовый доход?:', 'PProfile1'),
('currencyLabel', 'ru', 'Валюта:', 'PProfile1'),
('convertedIncomeLabel', 'ru', 'Конвертированный доход (PHP):', 'PProfile1'),
('nextButton', 'ru', 'Далее', 'PProfile1'),
('nationalityAmerican', 'ru', 'Американец', 'PProfile1'),
('nationalityFilipino', 'ru', 'Филиппинец', 'PProfile1'),
('sexMale', 'ru', 'Мужчина', 'PProfile1'),
('sexFemale', 'ru', 'Женщина', 'PProfile1'),
('civilStatusSingle', 'ru', 'Холост', 'PProfile1'),
('civilStatusMarried', 'ru', 'Женат/Гражданский брак', 'PProfile1'),
('invalidIncome', 'ru', 'Неверный доход', 'PProfile1');
