INSERT INTO localization00 (key, language_code, textcontent, component) VALUES
('surveyEvaluation05Header', 'en', 'Survey Evaluation', 'SurveyEvaluation05'),
('surveyEvaluation05Question1', 'en', 'Would you like to receive the overall results of the survey?', 'SurveyEvaluation05'),
('surveyEvaluation05OptionYes', 'en', 'Yes', 'SurveyEvaluation05'),
('surveyEvaluation05OptionNo', 'en', 'No', 'SurveyEvaluation05'),
('surveyEvaluation05Question2', 'en', 'In a scale of 1-4 (4 being the highest), how would you rate the survey?', 'SurveyEvaluation05'),
('surveyEvaluation05Question3', 'en', 'Do you think DOT and the LGUs should do this kind of surveys?', 'SurveyEvaluation05'),
('surveyEvaluation05OptionLike', 'en', 'I like them to do it', 'SurveyEvaluation05'),
('surveyEvaluation05OptionExpect', 'en', 'I expect that they should have been doing it', 'SurveyEvaluation05'),
('surveyEvaluation05OptionDontCare', 'en', 'I don''t care.', 'SurveyEvaluation05'),
('surveyEvaluation05OptionDontLike', 'en', 'I don''t like them doing it', 'SurveyEvaluation05'),
('surveyEvaluation05ButtonNext', 'en', 'Next', 'SurveyEvaluation05');

INSERT INTO localization00 (key, language_code, textcontent, component) VALUES
-- Korean Localizations
('surveyEvaluation05Header', 'ko', '설문 평가', 'SurveyEvaluation05'),
('surveyEvaluation05Question1', 'ko', '설문 조사 결과를 받으시겠습니까?', 'SurveyEvaluation05'),
('surveyEvaluation05OptionYes', 'ko', '예', 'SurveyEvaluation05'),
('surveyEvaluation05OptionNo', 'ko', '아니요', 'SurveyEvaluation05'),
('surveyEvaluation05Question2', 'ko', '1에서 4까지(4가 가장 높은 점수)로 설문을 어떻게 평가하시겠습니까?', 'SurveyEvaluation05'),
('surveyEvaluation05Question3', 'ko', 'DOT와 LGU가 이런 설문 조사를 해야 한다고 생각하십니까?', 'SurveyEvaluation05'),
('surveyEvaluation05OptionLike', 'ko', '그들이 이런 조사를 하길 바랍니다', 'SurveyEvaluation05'),
('surveyEvaluation05OptionExpect', 'ko', '그들이 이런 조사를 해왔어야 한다고 기대합니다', 'SurveyEvaluation05'),
('surveyEvaluation05OptionDontCare', 'ko', '상관 없습니다.', 'SurveyEvaluation05'),
('surveyEvaluation05OptionDontLike', 'ko', '그들이 이런 조사를 하는 것을 원치 않습니다', 'SurveyEvaluation05'),
('surveyEvaluation05ButtonNext', 'ko', '다음', 'SurveyEvaluation05'),

-- Chinese Localizations
('surveyEvaluation05Header', 'zh', '调查评估', 'SurveyEvaluation05'),
('surveyEvaluation05Question1', 'zh', '您想收到调查的总体结果吗？', 'SurveyEvaluation05'),
('surveyEvaluation05OptionYes', 'zh', '是', 'SurveyEvaluation05'),
('surveyEvaluation05OptionNo', 'zh', '否', 'SurveyEvaluation05'),
('surveyEvaluation05Question2', 'zh', '在1到4的范围内（4为最高），您会如何评价这次调查？', 'SurveyEvaluation05'),
('surveyEvaluation05Question3', 'zh', '您认为DOT和地方政府应该进行这类调查吗？', 'SurveyEvaluation05'),
('surveyEvaluation05OptionLike', 'zh', '我希望他们这样做', 'SurveyEvaluation05'),
('surveyEvaluation05OptionExpect', 'zh', '我期望他们早就这样做了', 'SurveyEvaluation05'),
('surveyEvaluation05OptionDontCare', 'zh', '我不在乎。', 'SurveyEvaluation05'),
('surveyEvaluation05OptionDontLike', 'zh', '我不喜欢他们这样做', 'SurveyEvaluation05'),
('surveyEvaluation05ButtonNext', 'zh', '下一步', 'SurveyEvaluation05'),

-- Japanese Localizations
('surveyEvaluation05Header', 'ja', 'アンケート評価', 'SurveyEvaluation05'),
('surveyEvaluation05Question1', 'ja', 'アンケートの全体結果を受け取りたいですか？', 'SurveyEvaluation05'),
('surveyEvaluation05OptionYes', 'ja', 'はい', 'SurveyEvaluation05'),
('surveyEvaluation05OptionNo', 'ja', 'いいえ', 'SurveyEvaluation05'),
('surveyEvaluation05Question2', 'ja', '1から4（4が最高）で、このアンケートをどう評価しますか？', 'SurveyEvaluation05'),
('surveyEvaluation05Question3', 'ja', 'DOTと地方自治体はこのようなアンケートを行うべきだと思いますか？', 'SurveyEvaluation05'),
('surveyEvaluation05OptionLike', 'ja', '彼らがそれを行うのが好きです', 'SurveyEvaluation05'),
('surveyEvaluation05OptionExpect', 'ja', '彼らがそれを行ってきたと期待します', 'SurveyEvaluation05'),
('surveyEvaluation05OptionDontCare', 'ja', '気にしません。', 'SurveyEvaluation05'),
('surveyEvaluation05OptionDontLike', 'ja', '彼らがそれを行うのが好きではありません', 'SurveyEvaluation05'),
('surveyEvaluation05ButtonNext', 'ja', '次へ', 'SurveyEvaluation05'),

-- Spanish Localizations
('surveyEvaluation05Header', 'es', 'Evaluación de la Encuesta', 'SurveyEvaluation05'),
('surveyEvaluation05Question1', 'es', '¿Le gustaría recibir los resultados generales de la encuesta?', 'SurveyEvaluation05'),
('surveyEvaluation05OptionYes', 'es', 'Sí', 'SurveyEvaluation05'),
('surveyEvaluation05OptionNo', 'es', 'No', 'SurveyEvaluation05'),
('surveyEvaluation05Question2', 'es', 'En una escala del 1 al 4 (siendo 4 el más alto), ¿cómo calificaría la encuesta?', 'SurveyEvaluation05'),
('surveyEvaluation05Question3', 'es', '¿Cree que DOT y los gobiernos locales deberían realizar este tipo de encuestas?', 'SurveyEvaluation05'),
('surveyEvaluation05OptionLike', 'es', 'Me gustaría que lo hicieran', 'SurveyEvaluation05'),
('surveyEvaluation05OptionExpect', 'es', 'Espero que lo hayan estado haciendo', 'SurveyEvaluation05'),
('surveyEvaluation05OptionDontCare', 'es', 'No me importa.', 'SurveyEvaluation05'),
('surveyEvaluation05OptionDontLike', 'es', 'No me gusta que lo hagan', 'SurveyEvaluation05'),
('surveyEvaluation05ButtonNext', 'es', 'Siguiente', 'SurveyEvaluation05'),

-- French Localizations
('surveyEvaluation05Header', 'fr', 'Évaluation du Sondage', 'SurveyEvaluation05'),
('surveyEvaluation05Question1', 'fr', 'Souhaitez-vous recevoir les résultats globaux du sondage ?', 'SurveyEvaluation05'),
('surveyEvaluation05OptionYes', 'fr', 'Oui', 'SurveyEvaluation05'),
('surveyEvaluation05OptionNo', 'fr', 'Non', 'SurveyEvaluation05'),
('surveyEvaluation05Question2', 'fr', 'Sur une échelle de 1 à 4 (4 étant le plus élevé), comment évalueriez-vous le sondage ?', 'SurveyEvaluation05'),
('surveyEvaluation05Question3', 'fr', 'Pensez-vous que le DOT et les collectivités locales devraient faire ce genre de sondages ?', 'SurveyEvaluation05'),
('surveyEvaluation05OptionLike', 'fr', 'Je veux qu’ils le fassent', 'SurveyEvaluation05'),
('surveyEvaluation05OptionExpect', 'fr', 'Je m’attends à ce qu’ils le fassent déjà', 'SurveyEvaluation05'),
('surveyEvaluation05OptionDontCare', 'fr', 'Cela m’est égal.', 'SurveyEvaluation05'),
('surveyEvaluation05OptionDontLike', 'fr', 'Je n’aime pas qu’ils le fassent', 'SurveyEvaluation05'),
('surveyEvaluation05ButtonNext', 'fr', 'Suivant', 'SurveyEvaluation05'),

-- Hindi Localizations
('surveyEvaluation05Header', 'hi', 'सर्वेक्षण मूल्यांकन', 'SurveyEvaluation05'),
('surveyEvaluation05Question1', 'hi', 'क्या आप सर्वेक्षण के कुल परिणाम प्राप्त करना चाहेंगे?', 'SurveyEvaluation05'),
('surveyEvaluation05OptionYes', 'hi', 'हाँ', 'SurveyEvaluation05'),
('surveyEvaluation05OptionNo', 'hi', 'नहीं', 'SurveyEvaluation05'),
('surveyEvaluation05Question2', 'hi', '1 से 4 के पैमाने पर (4 सबसे ऊँचा), आप सर्वेक्षण को कैसे रेट करेंगे?', 'SurveyEvaluation05'),
('surveyEvaluation05Question3', 'hi', 'क्या आपको लगता है कि DOT और स्थानीय निकायों को इस प्रकार के सर्वेक्षण करने चाहिए?', 'SurveyEvaluation05'),
('surveyEvaluation05OptionLike', 'hi', 'मुझे यह पसंद है कि वे इसे करें', 'SurveyEvaluation05'),
('surveyEvaluation05OptionExpect', 'hi', 'मुझे उम्मीद है कि वे इसे कर रहे होंगे', 'SurveyEvaluation05'),
('surveyEvaluation05OptionDontCare', 'hi', 'मुझे परवाह नहीं।', 'SurveyEvaluation05'),
('surveyEvaluation05OptionDontLike', 'hi', 'मुझे यह पसंद नहीं कि वे इसे करें', 'SurveyEvaluation05'),
('surveyEvaluation05ButtonNext', 'hi', 'आगे', 'SurveyEvaluation05'),

-- Russian Localizations
('surveyEvaluation05Header', 'ru', 'Оценка опроса', 'SurveyEvaluation05'),
('surveyEvaluation05Question1', 'ru', 'Хотите ли вы получить общие результаты опроса?', 'SurveyEvaluation05'),
('surveyEvaluation05OptionYes', 'ru', 'Да', 'SurveyEvaluation05'),
('surveyEvaluation05OptionNo', 'ru', 'Нет', 'SurveyEvaluation05'),
('surveyEvaluation05Question2', 'ru', 'По шкале от 1 до 4 (где 4 - наивысшая), как бы вы оценили опрос?', 'SurveyEvaluation05'),
('surveyEvaluation05Question3', 'ru', 'Считаете ли вы, что DOT и местные органы власти должны проводить такие опросы?', 'SurveyEvaluation05'),
('surveyEvaluation05OptionLike', 'ru', 'Мне нравится, что они это делают', 'SurveyEvaluation05'),
('surveyEvaluation05OptionExpect', 'ru', 'Я ожидаю, что они это делают', 'SurveyEvaluation05'),
('surveyEvaluation05OptionDontCare', 'ru', 'Мне все равно.', 'SurveyEvaluation05'),
('surveyEvaluation05OptionDontLike', 'ru', 'Мне не нравится, что они это делают', 'SurveyEvaluation05'),
('surveyEvaluation05ButtonNext', 'ru', 'Далее', 'SurveyEvaluation05');
