INSERT INTO localization00 (key, language_code, textcontent, component) VALUES
-- English
('transportation3RentalMotorcycleCarVan', 'en', 'Rental Motorcycle / Car / Van', 'Transportation3'),
('transportation3MotorcycleHabalHabal', 'en', 'Motorcycle (Habal-habal)', 'Transportation3'),
('transportation3BikePedicab', 'en', 'Bike / Pedicab', 'Transportation3'),
('transportation3Tricycle', 'en', 'Tricycle', 'Transportation3'),
('transportation3Jeepney', 'en', 'Jeepney', 'Transportation3'),
('transportation3Bus', 'en', 'Bus', 'Transportation3'),
('transportation3TaxiGrab', 'en', 'Taxi / Grab', 'Transportation3'),
('transportation3VanAUVPublicUtility', 'en', 'Van / AUV (public utility)', 'Transportation3'),
('transportation3SmallBoatBangka', 'en', 'Small Boat (Bangka)', 'Transportation3'),
('transportation3FerryCommercialShipBig', 'en', 'Ferry / Commercial Ship (big)', 'Transportation3'),
('transportation3TrainMRTLRT', 'en', 'Train (e.g. MRT, LRT, PNR)', 'Transportation3'),
('transportation3PrivateVehicleNoNeedToRate', 'en', 'Private Vehicle (No need to rate)', 'Transportation3'),
('transportation3PleaseRateThisTouristAttractionEvent', 'en', 'Please rate the following Transportation modes that you have used during your time here. You can also answer the second choice (neutral) if you have never tried it before:', 'Transportation3'),

-- Korean
('transportation3RentalMotorcycleCarVan', 'ko', '렌탈 오토바이 / 자동차 / 밴', 'Transportation3'),
('transportation3MotorcycleHabalHabal', 'ko', '오토바이 (하발하발)', 'Transportation3'),
('transportation3BikePedicab', 'ko', '자전거 / 인력거', 'Transportation3'),
('transportation3Tricycle', 'ko', '삼륜차', 'Transportation3'),
('transportation3Jeepney', 'ko', '지프니', 'Transportation3'),
('transportation3Bus', 'ko', '버스', 'Transportation3'),
('transportation3TaxiGrab', 'ko', '택시 / 그랩', 'Transportation3'),
('transportation3VanAUVPublicUtility', 'ko', '밴 / 다목적 차량 (공공용)', 'Transportation3'),
('transportation3SmallBoatBangka', 'ko', '작은 보트 (방카)', 'Transportation3'),
('transportation3FerryCommercialShipBig', 'ko', '페리 / 상업용 대형 선박', 'Transportation3'),
('transportation3TrainMRTLRT', 'ko', '기차 (예: MRT, LRT, PNR)', 'Transportation3'),
('transportation3PrivateVehicleNoNeedToRate', 'ko', '개인 차량 (평가 불필요)', 'Transportation3'),
('transportation3PleaseRateThisTouristAttractionEvent', 'ko', '여기서 사용한 교통수단을 평가해주세요. 사용해본 적이 없다면 두 번째 선택(중립)을 선택할 수도 있습니다.', 'Transportation3'),

-- Chinese
('transportation3RentalMotorcycleCarVan', 'zh', '租用摩托车 / 汽车 / 面包车', 'Transportation3'),
('transportation3MotorcycleHabalHabal', 'zh', '摩托车 (Habal-habal)', 'Transportation3'),
('transportation3BikePedicab', 'zh', '自行车 / 人力车', 'Transportation3'),
('transportation3Tricycle', 'zh', '三轮车', 'Transportation3'),
('transportation3Jeepney', 'zh', '吉普尼', 'Transportation3'),
('transportation3Bus', 'zh', '巴士', 'Transportation3'),
('transportation3TaxiGrab', 'zh', '出租车 / Grab', 'Transportation3'),
('transportation3VanAUVPublicUtility', 'zh', '面包车 / 多用途车 (公共用途)', 'Transportation3'),
('transportation3SmallBoatBangka', 'zh', '小船 (Bangka)', 'Transportation3'),
('transportation3FerryCommercialShipBig', 'zh', '渡轮 / 商业大船', 'Transportation3'),
('transportation3TrainMRTLRT', 'zh', '火车 (例如: MRT, LRT, PNR)', 'Transportation3'),
('transportation3PrivateVehicleNoNeedToRate', 'zh', '私人车辆 (无需评分)', 'Transportation3'),
('transportation3PleaseRateThisTouristAttractionEvent', 'zh', '请评价您在此期间使用的交通工具。如果您从未使用过，也可以选择第二个选项（中立）。', 'Transportation3'),

-- Japanese
('transportation3RentalMotorcycleCarVan', 'ja', 'レンタルバイク / 車 / バン', 'Transportation3'),
('transportation3MotorcycleHabalHabal', 'ja', 'バイク (ハバルハバル)', 'Transportation3'),
('transportation3BikePedicab', 'ja', '自転車 / ペディキャブ', 'Transportation3'),
('transportation3Tricycle', 'ja', '三輪車', 'Transportation3'),
('transportation3Jeepney', 'ja', 'ジープニー', 'Transportation3'),
('transportation3Bus', 'ja', 'バス', 'Transportation3'),
('transportation3TaxiGrab', 'ja', 'タクシー / グラブ', 'Transportation3'),
('transportation3VanAUVPublicUtility', 'ja', 'バン / 多目的車 (公共利用)', 'Transportation3'),
('transportation3SmallBoatBangka', 'ja', '小型ボート (バンカ)', 'Transportation3'),
('transportation3FerryCommercialShipBig', 'ja', 'フェリー / 商業用大型船', 'Transportation3'),
('transportation3TrainMRTLRT', 'ja', '電車 (例: MRT, LRT, PNR)', 'Transportation3'),
('transportation3PrivateVehicleNoNeedToRate', 'ja', '自家用車 (評価不要)', 'Transportation3'),
('transportation3PleaseRateThisTouristAttractionEvent', 'ja', 'ここで利用した交通手段を評価してください。利用したことがない場合は、2番目の選択肢（中立）を選択することもできます。', 'Transportation3'),

-- Spanish
('transportation3RentalMotorcycleCarVan', 'es', 'Moto / Coche / Furgoneta de alquiler', 'Transportation3'),
('transportation3MotorcycleHabalHabal', 'es', 'Motocicleta (Habal-habal)', 'Transportation3'),
('transportation3BikePedicab', 'es', 'Bicicleta / Bicitaxi', 'Transportation3'),
('transportation3Tricycle', 'es', 'Triciclo', 'Transportation3'),
('transportation3Jeepney', 'es', 'Jeepney', 'Transportation3'),
('transportation3Bus', 'es', 'Autobús', 'Transportation3'),
('transportation3TaxiGrab', 'es', 'Taxi / Grab', 'Transportation3'),
('transportation3VanAUVPublicUtility', 'es', 'Furgoneta / AUV (uso público)', 'Transportation3'),
('transportation3SmallBoatBangka', 'es', 'Barco pequeño (Bangka)', 'Transportation3'),
('transportation3FerryCommercialShipBig', 'es', 'Ferry / Barco comercial grande', 'Transportation3'),
('transportation3TrainMRTLRT', 'es', 'Tren (p. ej.: MRT, LRT, PNR)', 'Transportation3'),
('transportation3PrivateVehicleNoNeedToRate', 'es', 'Vehículo privado (no es necesario calificar)', 'Transportation3'),
('transportation3PleaseRateThisTouristAttractionEvent', 'es', 'Por favor, califica los siguientes medios de transporte que has utilizado durante tu estancia aquí. También puedes responder la segunda opción (neutral) si nunca lo has probado:', 'Transportation3'),

-- French
('transportation3RentalMotorcycleCarVan', 'fr', 'Moto / Voiture / Van de location', 'Transportation3'),
('transportation3MotorcycleHabalHabal', 'fr', 'Moto (Habal-habal)', 'Transportation3'),
('transportation3BikePedicab', 'fr', 'Vélo / Pousse-pousse', 'Transportation3'),
('transportation3Tricycle', 'fr', 'Tricycle', 'Transportation3'),
('transportation3Jeepney', 'fr', 'Jeepney', 'Transportation3'),
('transportation3Bus', 'fr', 'Bus', 'Transportation3'),
('transportation3TaxiGrab', 'fr', 'Taxi / Grab', 'Transportation3'),
('transportation3VanAUVPublicUtility', 'fr', 'Van / AUV (usage public)', 'Transportation3'),
('transportation3SmallBoatBangka', 'fr', 'Petit bateau (Bangka)', 'Transportation3'),
('transportation3FerryCommercialShipBig', 'fr', 'Ferry / Navire commercial (grand)', 'Transportation3'),
('transportation3TrainMRTLRT', 'fr', 'Train (par ex. MRT, LRT, PNR)', 'Transportation3'),
('transportation3PrivateVehicleNoNeedToRate', 'fr', 'Véhicule privé (Pas besoin d’évaluer)', 'Transportation3'),
('transportation3PleaseRateThisTouristAttractionEvent', 'fr', 'Veuillez évaluer les modes de transport suivants que vous avez utilisés pendant votre séjour ici. Vous pouvez également choisir la deuxième option (neutre) si vous ne les avez jamais essayés :', 'Transportation3'),

-- Hindi
('transportation3RentalMotorcycleCarVan', 'hi', 'किराये की मोटरसाइकिल / कार / वैन', 'Transportation3'),
('transportation3MotorcycleHabalHabal', 'hi', 'मोटरसाइकिल (हबल-हबल)', 'Transportation3'),
('transportation3BikePedicab', 'hi', 'साइकिल / पैडिकैब', 'Transportation3'),
('transportation3Tricycle', 'hi', 'त्रिचक्री', 'Transportation3'),
('transportation3Jeepney', 'hi', 'जीपनी', 'Transportation3'),
('transportation3Bus', 'hi', 'बस', 'Transportation3'),
('transportation3TaxiGrab', 'hi', 'टैक्सी / ग्रैब', 'Transportation3'),
('transportation3VanAUVPublicUtility', 'hi', 'वैन / एयूवी (सार्वजनिक उपयोगिता)', 'Transportation3'),
('transportation3SmallBoatBangka', 'hi', 'छोटी नाव (बंका)', 'Transportation3'),
('transportation3FerryCommercialShipBig', 'hi', 'फेरी / वाणिज्यिक जहाज (बड़ा)', 'Transportation3'),
('transportation3TrainMRTLRT', 'hi', 'ट्रेन (उदा: एमआरटी, एलआरटी, पीएनआर)', 'Transportation3'),
('transportation3PrivateVehicleNoNeedToRate', 'hi', 'निजी वाहन (रेट करने की आवश्यकता नहीं)', 'Transportation3'),
('transportation3PleaseRateThisTouristAttractionEvent', 'hi', 'कृपया उन परिवहन साधनों को रेट करें जो आपने यहां रहने के दौरान उपयोग किए हैं। यदि आपने इसे कभी आजमाया नहीं है तो आप दूसरा विकल्प (तटस्थ) भी चुन सकते हैं:', 'Transportation3'),

-- Russian
('transportation3RentalMotorcycleCarVan', 'ru', 'Прокат мотоцикла / автомобиля / фургона', 'Transportation3'),
('transportation3MotorcycleHabalHabal', 'ru', 'Мотоцикл (Хабал-хабал)', 'Transportation3'),
('transportation3BikePedicab', 'ru', 'Велосипед / велорикша', 'Transportation3'),
('transportation3Tricycle', 'ru', 'Трицикл', 'Transportation3'),
('transportation3Jeepney', 'ru', 'Джипни', 'Transportation3'),
('transportation3Bus', 'ru', 'Автобус', 'Transportation3'),
('transportation3TaxiGrab', 'ru', 'Такси / Граб', 'Transportation3'),
('transportation3VanAUVPublicUtility', 'ru', 'Фургон / AUV (общественная утилита)', 'Transportation3'),
('transportation3SmallBoatBangka', 'ru', 'Маленькая лодка (Банка)', 'Transportation3'),
('transportation3FerryCommercialShipBig', 'ru', 'Паром / коммерческое судно (большое)', 'Transportation3'),
('transportation3TrainMRTLRT', 'ru', 'Поезд (например, MRT, LRT, PNR)', 'Transportation3'),
('transportation3PrivateVehicleNoNeedToRate', 'ru', 'Личное транспортное средство (не нужно оценивать)', 'Transportation3'),
('transportation3PleaseRateThisTouristAttractionEvent', 'ru', 'Пожалуйста, оцените следующие виды транспорта, которые вы использовали во время своего пребывания здесь. Вы также можете выбрать второй вариант (нейтрально), если вы никогда не пробовали:', 'Transportation3');
